// Generates pure Verilog combinational logic (MUX) from a list of validated hex codes.
// Ensures that the generated ROM does not exceed the 16-bit address space
// Returns a Result containing the verilog code string or an error message.
pub fn generate_verilog_content(hex_codes: &[String]) -> Result<String, String> {
    // Limit Check
    let max_address = 65536; // 16-bit address space limit (2^16)

    if hex_codes.len() > max_address {
        return Err(format!(
            "Memory Overflow Error: Cannot generate ROM. The provided {} instructions exceed the 16-bit architectural limit of {}.",
            hex_codes.len(),
            max_address
        ));
    }

    // Memory Optimization: Pre-allocate capacity to prevent multiple re-allocations
    // Approximate size: Base header size + (~64 bytes per instruction line)
    let mut verilog = String::with_capacity(2048 + (hex_codes.len() * 64));

    // File Header
    verilog.push_str("// ============================================================================\n");
    verilog.push_str("// WARNING: THIS FILE WAS AUTO-GENERATED BY RUST ROM_BUILDER!\n");
    verilog.push_str("// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN DURING SYNTHESIS.\n");
    verilog.push_str("// ============================================================================\n");
    verilog.push_str("`timescale 1ns / 1ps\n\n");

    verilog.push_str("module instruction_memory (\n");
    verilog.push_str("    input  wire [15:0] read_addr,\n");
    verilog.push_str("    output reg  [15:0] instruction_out\n");
    verilog.push_str(");\n\n");

    // Combinational MUX Logic
    verilog.push_str("    // Combinational MUX Logic (Synthesizes directly to ROM gates)\n");
    verilog.push_str("    always @(*) begin\n");
    verilog.push_str("        case (read_addr)\n");

    // Instruction Mapping
    for (address, hex_code) in hex_codes.iter().enumerate() {
        verilog.push_str(&format!(
                    "            16'h{:04X}: instruction_out = 16'h{};\n",
                    address, hex_code
        ));
    }

    // Default fallback (Hardware Security against Floating Latches)
    verilog.push_str("\n            // Default safety ground to prevent floating wires (Latch Inference)\n");
    verilog.push_str("            default: instruction_out = 16'h0000;\n");
    verilog.push_str("        endcase\n");
    verilog.push_str("    end\n");

    verilog.push_str("endmodule\n");

    Ok(verilog)
}