`timescale 1ns / 1ps
// ============================================================================
// WARNING: THIS FILE WAS AUTO-GENERATED BY RUST RAM_BUILDER!
// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
// ============================================================================

module data_memory (
    input wire clk,
    input wire rst,
    input wire we,              // Global Write Enable
    input wire [7:0] addr,
    input wire [7:0] data_in,
    output wire [7:0] data_out
);

    // --- Internal Wires ---
    wire [7:0] mem_out_00;
    wire we_00;
    wire [7:0] mem_out_01;
    wire we_01;
    wire [7:0] mem_out_02;
    wire we_02;
    wire [7:0] mem_out_03;
    wire we_03;
    wire [7:0] mem_out_04;
    wire we_04;
    wire [7:0] mem_out_05;
    wire we_05;
    wire [7:0] mem_out_06;
    wire we_06;
    wire [7:0] mem_out_07;
    wire we_07;
    wire [7:0] mem_out_08;
    wire we_08;
    wire [7:0] mem_out_09;
    wire we_09;
    wire [7:0] mem_out_0A;
    wire we_0A;
    wire [7:0] mem_out_0B;
    wire we_0B;
    wire [7:0] mem_out_0C;
    wire we_0C;
    wire [7:0] mem_out_0D;
    wire we_0D;
    wire [7:0] mem_out_0E;
    wire we_0E;
    wire [7:0] mem_out_0F;
    wire we_0F;
    wire [7:0] mem_out_10;
    wire we_10;
    wire [7:0] mem_out_11;
    wire we_11;
    wire [7:0] mem_out_12;
    wire we_12;
    wire [7:0] mem_out_13;
    wire we_13;
    wire [7:0] mem_out_14;
    wire we_14;
    wire [7:0] mem_out_15;
    wire we_15;
    wire [7:0] mem_out_16;
    wire we_16;
    wire [7:0] mem_out_17;
    wire we_17;
    wire [7:0] mem_out_18;
    wire we_18;
    wire [7:0] mem_out_19;
    wire we_19;
    wire [7:0] mem_out_1A;
    wire we_1A;
    wire [7:0] mem_out_1B;
    wire we_1B;
    wire [7:0] mem_out_1C;
    wire we_1C;
    wire [7:0] mem_out_1D;
    wire we_1D;
    wire [7:0] mem_out_1E;
    wire we_1E;
    wire [7:0] mem_out_1F;
    wire we_1F;
    wire [7:0] mem_out_20;
    wire we_20;
    wire [7:0] mem_out_21;
    wire we_21;
    wire [7:0] mem_out_22;
    wire we_22;
    wire [7:0] mem_out_23;
    wire we_23;
    wire [7:0] mem_out_24;
    wire we_24;
    wire [7:0] mem_out_25;
    wire we_25;
    wire [7:0] mem_out_26;
    wire we_26;
    wire [7:0] mem_out_27;
    wire we_27;
    wire [7:0] mem_out_28;
    wire we_28;
    wire [7:0] mem_out_29;
    wire we_29;
    wire [7:0] mem_out_2A;
    wire we_2A;
    wire [7:0] mem_out_2B;
    wire we_2B;
    wire [7:0] mem_out_2C;
    wire we_2C;
    wire [7:0] mem_out_2D;
    wire we_2D;
    wire [7:0] mem_out_2E;
    wire we_2E;
    wire [7:0] mem_out_2F;
    wire we_2F;
    wire [7:0] mem_out_30;
    wire we_30;
    wire [7:0] mem_out_31;
    wire we_31;
    wire [7:0] mem_out_32;
    wire we_32;
    wire [7:0] mem_out_33;
    wire we_33;
    wire [7:0] mem_out_34;
    wire we_34;
    wire [7:0] mem_out_35;
    wire we_35;
    wire [7:0] mem_out_36;
    wire we_36;
    wire [7:0] mem_out_37;
    wire we_37;
    wire [7:0] mem_out_38;
    wire we_38;
    wire [7:0] mem_out_39;
    wire we_39;
    wire [7:0] mem_out_3A;
    wire we_3A;
    wire [7:0] mem_out_3B;
    wire we_3B;
    wire [7:0] mem_out_3C;
    wire we_3C;
    wire [7:0] mem_out_3D;
    wire we_3D;
    wire [7:0] mem_out_3E;
    wire we_3E;
    wire [7:0] mem_out_3F;
    wire we_3F;
    wire [7:0] mem_out_40;
    wire we_40;
    wire [7:0] mem_out_41;
    wire we_41;
    wire [7:0] mem_out_42;
    wire we_42;
    wire [7:0] mem_out_43;
    wire we_43;
    wire [7:0] mem_out_44;
    wire we_44;
    wire [7:0] mem_out_45;
    wire we_45;
    wire [7:0] mem_out_46;
    wire we_46;
    wire [7:0] mem_out_47;
    wire we_47;
    wire [7:0] mem_out_48;
    wire we_48;
    wire [7:0] mem_out_49;
    wire we_49;
    wire [7:0] mem_out_4A;
    wire we_4A;
    wire [7:0] mem_out_4B;
    wire we_4B;
    wire [7:0] mem_out_4C;
    wire we_4C;
    wire [7:0] mem_out_4D;
    wire we_4D;
    wire [7:0] mem_out_4E;
    wire we_4E;
    wire [7:0] mem_out_4F;
    wire we_4F;
    wire [7:0] mem_out_50;
    wire we_50;
    wire [7:0] mem_out_51;
    wire we_51;
    wire [7:0] mem_out_52;
    wire we_52;
    wire [7:0] mem_out_53;
    wire we_53;
    wire [7:0] mem_out_54;
    wire we_54;
    wire [7:0] mem_out_55;
    wire we_55;
    wire [7:0] mem_out_56;
    wire we_56;
    wire [7:0] mem_out_57;
    wire we_57;
    wire [7:0] mem_out_58;
    wire we_58;
    wire [7:0] mem_out_59;
    wire we_59;
    wire [7:0] mem_out_5A;
    wire we_5A;
    wire [7:0] mem_out_5B;
    wire we_5B;
    wire [7:0] mem_out_5C;
    wire we_5C;
    wire [7:0] mem_out_5D;
    wire we_5D;
    wire [7:0] mem_out_5E;
    wire we_5E;
    wire [7:0] mem_out_5F;
    wire we_5F;
    wire [7:0] mem_out_60;
    wire we_60;
    wire [7:0] mem_out_61;
    wire we_61;
    wire [7:0] mem_out_62;
    wire we_62;
    wire [7:0] mem_out_63;
    wire we_63;
    wire [7:0] mem_out_64;
    wire we_64;
    wire [7:0] mem_out_65;
    wire we_65;
    wire [7:0] mem_out_66;
    wire we_66;
    wire [7:0] mem_out_67;
    wire we_67;
    wire [7:0] mem_out_68;
    wire we_68;
    wire [7:0] mem_out_69;
    wire we_69;
    wire [7:0] mem_out_6A;
    wire we_6A;
    wire [7:0] mem_out_6B;
    wire we_6B;
    wire [7:0] mem_out_6C;
    wire we_6C;
    wire [7:0] mem_out_6D;
    wire we_6D;
    wire [7:0] mem_out_6E;
    wire we_6E;
    wire [7:0] mem_out_6F;
    wire we_6F;
    wire [7:0] mem_out_70;
    wire we_70;
    wire [7:0] mem_out_71;
    wire we_71;
    wire [7:0] mem_out_72;
    wire we_72;
    wire [7:0] mem_out_73;
    wire we_73;
    wire [7:0] mem_out_74;
    wire we_74;
    wire [7:0] mem_out_75;
    wire we_75;
    wire [7:0] mem_out_76;
    wire we_76;
    wire [7:0] mem_out_77;
    wire we_77;
    wire [7:0] mem_out_78;
    wire we_78;
    wire [7:0] mem_out_79;
    wire we_79;
    wire [7:0] mem_out_7A;
    wire we_7A;
    wire [7:0] mem_out_7B;
    wire we_7B;
    wire [7:0] mem_out_7C;
    wire we_7C;
    wire [7:0] mem_out_7D;
    wire we_7D;
    wire [7:0] mem_out_7E;
    wire we_7E;
    wire [7:0] mem_out_7F;
    wire we_7F;
    wire [7:0] mem_out_80;
    wire we_80;
    wire [7:0] mem_out_81;
    wire we_81;
    wire [7:0] mem_out_82;
    wire we_82;
    wire [7:0] mem_out_83;
    wire we_83;
    wire [7:0] mem_out_84;
    wire we_84;
    wire [7:0] mem_out_85;
    wire we_85;
    wire [7:0] mem_out_86;
    wire we_86;
    wire [7:0] mem_out_87;
    wire we_87;
    wire [7:0] mem_out_88;
    wire we_88;
    wire [7:0] mem_out_89;
    wire we_89;
    wire [7:0] mem_out_8A;
    wire we_8A;
    wire [7:0] mem_out_8B;
    wire we_8B;
    wire [7:0] mem_out_8C;
    wire we_8C;
    wire [7:0] mem_out_8D;
    wire we_8D;
    wire [7:0] mem_out_8E;
    wire we_8E;
    wire [7:0] mem_out_8F;
    wire we_8F;
    wire [7:0] mem_out_90;
    wire we_90;
    wire [7:0] mem_out_91;
    wire we_91;
    wire [7:0] mem_out_92;
    wire we_92;
    wire [7:0] mem_out_93;
    wire we_93;
    wire [7:0] mem_out_94;
    wire we_94;
    wire [7:0] mem_out_95;
    wire we_95;
    wire [7:0] mem_out_96;
    wire we_96;
    wire [7:0] mem_out_97;
    wire we_97;
    wire [7:0] mem_out_98;
    wire we_98;
    wire [7:0] mem_out_99;
    wire we_99;
    wire [7:0] mem_out_9A;
    wire we_9A;
    wire [7:0] mem_out_9B;
    wire we_9B;
    wire [7:0] mem_out_9C;
    wire we_9C;
    wire [7:0] mem_out_9D;
    wire we_9D;
    wire [7:0] mem_out_9E;
    wire we_9E;
    wire [7:0] mem_out_9F;
    wire we_9F;
    wire [7:0] mem_out_A0;
    wire we_A0;
    wire [7:0] mem_out_A1;
    wire we_A1;
    wire [7:0] mem_out_A2;
    wire we_A2;
    wire [7:0] mem_out_A3;
    wire we_A3;
    wire [7:0] mem_out_A4;
    wire we_A4;
    wire [7:0] mem_out_A5;
    wire we_A5;
    wire [7:0] mem_out_A6;
    wire we_A6;
    wire [7:0] mem_out_A7;
    wire we_A7;
    wire [7:0] mem_out_A8;
    wire we_A8;
    wire [7:0] mem_out_A9;
    wire we_A9;
    wire [7:0] mem_out_AA;
    wire we_AA;
    wire [7:0] mem_out_AB;
    wire we_AB;
    wire [7:0] mem_out_AC;
    wire we_AC;
    wire [7:0] mem_out_AD;
    wire we_AD;
    wire [7:0] mem_out_AE;
    wire we_AE;
    wire [7:0] mem_out_AF;
    wire we_AF;
    wire [7:0] mem_out_B0;
    wire we_B0;
    wire [7:0] mem_out_B1;
    wire we_B1;
    wire [7:0] mem_out_B2;
    wire we_B2;
    wire [7:0] mem_out_B3;
    wire we_B3;
    wire [7:0] mem_out_B4;
    wire we_B4;
    wire [7:0] mem_out_B5;
    wire we_B5;
    wire [7:0] mem_out_B6;
    wire we_B6;
    wire [7:0] mem_out_B7;
    wire we_B7;
    wire [7:0] mem_out_B8;
    wire we_B8;
    wire [7:0] mem_out_B9;
    wire we_B9;
    wire [7:0] mem_out_BA;
    wire we_BA;
    wire [7:0] mem_out_BB;
    wire we_BB;
    wire [7:0] mem_out_BC;
    wire we_BC;
    wire [7:0] mem_out_BD;
    wire we_BD;
    wire [7:0] mem_out_BE;
    wire we_BE;
    wire [7:0] mem_out_BF;
    wire we_BF;
    wire [7:0] mem_out_C0;
    wire we_C0;
    wire [7:0] mem_out_C1;
    wire we_C1;
    wire [7:0] mem_out_C2;
    wire we_C2;
    wire [7:0] mem_out_C3;
    wire we_C3;
    wire [7:0] mem_out_C4;
    wire we_C4;
    wire [7:0] mem_out_C5;
    wire we_C5;
    wire [7:0] mem_out_C6;
    wire we_C6;
    wire [7:0] mem_out_C7;
    wire we_C7;
    wire [7:0] mem_out_C8;
    wire we_C8;
    wire [7:0] mem_out_C9;
    wire we_C9;
    wire [7:0] mem_out_CA;
    wire we_CA;
    wire [7:0] mem_out_CB;
    wire we_CB;
    wire [7:0] mem_out_CC;
    wire we_CC;
    wire [7:0] mem_out_CD;
    wire we_CD;
    wire [7:0] mem_out_CE;
    wire we_CE;
    wire [7:0] mem_out_CF;
    wire we_CF;
    wire [7:0] mem_out_D0;
    wire we_D0;
    wire [7:0] mem_out_D1;
    wire we_D1;
    wire [7:0] mem_out_D2;
    wire we_D2;
    wire [7:0] mem_out_D3;
    wire we_D3;
    wire [7:0] mem_out_D4;
    wire we_D4;
    wire [7:0] mem_out_D5;
    wire we_D5;
    wire [7:0] mem_out_D6;
    wire we_D6;
    wire [7:0] mem_out_D7;
    wire we_D7;
    wire [7:0] mem_out_D8;
    wire we_D8;
    wire [7:0] mem_out_D9;
    wire we_D9;
    wire [7:0] mem_out_DA;
    wire we_DA;
    wire [7:0] mem_out_DB;
    wire we_DB;
    wire [7:0] mem_out_DC;
    wire we_DC;
    wire [7:0] mem_out_DD;
    wire we_DD;
    wire [7:0] mem_out_DE;
    wire we_DE;
    wire [7:0] mem_out_DF;
    wire we_DF;
    wire [7:0] mem_out_E0;
    wire we_E0;
    wire [7:0] mem_out_E1;
    wire we_E1;
    wire [7:0] mem_out_E2;
    wire we_E2;
    wire [7:0] mem_out_E3;
    wire we_E3;
    wire [7:0] mem_out_E4;
    wire we_E4;
    wire [7:0] mem_out_E5;
    wire we_E5;
    wire [7:0] mem_out_E6;
    wire we_E6;
    wire [7:0] mem_out_E7;
    wire we_E7;
    wire [7:0] mem_out_E8;
    wire we_E8;
    wire [7:0] mem_out_E9;
    wire we_E9;
    wire [7:0] mem_out_EA;
    wire we_EA;
    wire [7:0] mem_out_EB;
    wire we_EB;
    wire [7:0] mem_out_EC;
    wire we_EC;
    wire [7:0] mem_out_ED;
    wire we_ED;
    wire [7:0] mem_out_EE;
    wire we_EE;
    wire [7:0] mem_out_EF;
    wire we_EF;
    wire [7:0] mem_out_F0;
    wire we_F0;
    wire [7:0] mem_out_F1;
    wire we_F1;
    wire [7:0] mem_out_F2;
    wire we_F2;
    wire [7:0] mem_out_F3;
    wire we_F3;
    wire [7:0] mem_out_F4;
    wire we_F4;
    wire [7:0] mem_out_F5;
    wire we_F5;
    wire [7:0] mem_out_F6;
    wire we_F6;
    wire [7:0] mem_out_F7;
    wire we_F7;
    wire [7:0] mem_out_F8;
    wire we_F8;
    wire [7:0] mem_out_F9;
    wire we_F9;
    wire [7:0] mem_out_FA;
    wire we_FA;
    wire [7:0] mem_out_FB;
    wire we_FB;
    wire [7:0] mem_out_FC;
    wire we_FC;
    wire [7:0] mem_out_FD;
    wire we_FD;
    wire [7:0] mem_out_FE;
    wire we_FE;
    wire [7:0] mem_out_FF;
    wire we_FF;

    // --- Write Address Decoder (8-to-256 DEMUX) ---
    assign we_00 = we & ~|(addr ^ 8'h00);
    assign we_01 = we & ~|(addr ^ 8'h01);
    assign we_02 = we & ~|(addr ^ 8'h02);
    assign we_03 = we & ~|(addr ^ 8'h03);
    assign we_04 = we & ~|(addr ^ 8'h04);
    assign we_05 = we & ~|(addr ^ 8'h05);
    assign we_06 = we & ~|(addr ^ 8'h06);
    assign we_07 = we & ~|(addr ^ 8'h07);
    assign we_08 = we & ~|(addr ^ 8'h08);
    assign we_09 = we & ~|(addr ^ 8'h09);
    assign we_0A = we & ~|(addr ^ 8'h0A);
    assign we_0B = we & ~|(addr ^ 8'h0B);
    assign we_0C = we & ~|(addr ^ 8'h0C);
    assign we_0D = we & ~|(addr ^ 8'h0D);
    assign we_0E = we & ~|(addr ^ 8'h0E);
    assign we_0F = we & ~|(addr ^ 8'h0F);
    assign we_10 = we & ~|(addr ^ 8'h10);
    assign we_11 = we & ~|(addr ^ 8'h11);
    assign we_12 = we & ~|(addr ^ 8'h12);
    assign we_13 = we & ~|(addr ^ 8'h13);
    assign we_14 = we & ~|(addr ^ 8'h14);
    assign we_15 = we & ~|(addr ^ 8'h15);
    assign we_16 = we & ~|(addr ^ 8'h16);
    assign we_17 = we & ~|(addr ^ 8'h17);
    assign we_18 = we & ~|(addr ^ 8'h18);
    assign we_19 = we & ~|(addr ^ 8'h19);
    assign we_1A = we & ~|(addr ^ 8'h1A);
    assign we_1B = we & ~|(addr ^ 8'h1B);
    assign we_1C = we & ~|(addr ^ 8'h1C);
    assign we_1D = we & ~|(addr ^ 8'h1D);
    assign we_1E = we & ~|(addr ^ 8'h1E);
    assign we_1F = we & ~|(addr ^ 8'h1F);
    assign we_20 = we & ~|(addr ^ 8'h20);
    assign we_21 = we & ~|(addr ^ 8'h21);
    assign we_22 = we & ~|(addr ^ 8'h22);
    assign we_23 = we & ~|(addr ^ 8'h23);
    assign we_24 = we & ~|(addr ^ 8'h24);
    assign we_25 = we & ~|(addr ^ 8'h25);
    assign we_26 = we & ~|(addr ^ 8'h26);
    assign we_27 = we & ~|(addr ^ 8'h27);
    assign we_28 = we & ~|(addr ^ 8'h28);
    assign we_29 = we & ~|(addr ^ 8'h29);
    assign we_2A = we & ~|(addr ^ 8'h2A);
    assign we_2B = we & ~|(addr ^ 8'h2B);
    assign we_2C = we & ~|(addr ^ 8'h2C);
    assign we_2D = we & ~|(addr ^ 8'h2D);
    assign we_2E = we & ~|(addr ^ 8'h2E);
    assign we_2F = we & ~|(addr ^ 8'h2F);
    assign we_30 = we & ~|(addr ^ 8'h30);
    assign we_31 = we & ~|(addr ^ 8'h31);
    assign we_32 = we & ~|(addr ^ 8'h32);
    assign we_33 = we & ~|(addr ^ 8'h33);
    assign we_34 = we & ~|(addr ^ 8'h34);
    assign we_35 = we & ~|(addr ^ 8'h35);
    assign we_36 = we & ~|(addr ^ 8'h36);
    assign we_37 = we & ~|(addr ^ 8'h37);
    assign we_38 = we & ~|(addr ^ 8'h38);
    assign we_39 = we & ~|(addr ^ 8'h39);
    assign we_3A = we & ~|(addr ^ 8'h3A);
    assign we_3B = we & ~|(addr ^ 8'h3B);
    assign we_3C = we & ~|(addr ^ 8'h3C);
    assign we_3D = we & ~|(addr ^ 8'h3D);
    assign we_3E = we & ~|(addr ^ 8'h3E);
    assign we_3F = we & ~|(addr ^ 8'h3F);
    assign we_40 = we & ~|(addr ^ 8'h40);
    assign we_41 = we & ~|(addr ^ 8'h41);
    assign we_42 = we & ~|(addr ^ 8'h42);
    assign we_43 = we & ~|(addr ^ 8'h43);
    assign we_44 = we & ~|(addr ^ 8'h44);
    assign we_45 = we & ~|(addr ^ 8'h45);
    assign we_46 = we & ~|(addr ^ 8'h46);
    assign we_47 = we & ~|(addr ^ 8'h47);
    assign we_48 = we & ~|(addr ^ 8'h48);
    assign we_49 = we & ~|(addr ^ 8'h49);
    assign we_4A = we & ~|(addr ^ 8'h4A);
    assign we_4B = we & ~|(addr ^ 8'h4B);
    assign we_4C = we & ~|(addr ^ 8'h4C);
    assign we_4D = we & ~|(addr ^ 8'h4D);
    assign we_4E = we & ~|(addr ^ 8'h4E);
    assign we_4F = we & ~|(addr ^ 8'h4F);
    assign we_50 = we & ~|(addr ^ 8'h50);
    assign we_51 = we & ~|(addr ^ 8'h51);
    assign we_52 = we & ~|(addr ^ 8'h52);
    assign we_53 = we & ~|(addr ^ 8'h53);
    assign we_54 = we & ~|(addr ^ 8'h54);
    assign we_55 = we & ~|(addr ^ 8'h55);
    assign we_56 = we & ~|(addr ^ 8'h56);
    assign we_57 = we & ~|(addr ^ 8'h57);
    assign we_58 = we & ~|(addr ^ 8'h58);
    assign we_59 = we & ~|(addr ^ 8'h59);
    assign we_5A = we & ~|(addr ^ 8'h5A);
    assign we_5B = we & ~|(addr ^ 8'h5B);
    assign we_5C = we & ~|(addr ^ 8'h5C);
    assign we_5D = we & ~|(addr ^ 8'h5D);
    assign we_5E = we & ~|(addr ^ 8'h5E);
    assign we_5F = we & ~|(addr ^ 8'h5F);
    assign we_60 = we & ~|(addr ^ 8'h60);
    assign we_61 = we & ~|(addr ^ 8'h61);
    assign we_62 = we & ~|(addr ^ 8'h62);
    assign we_63 = we & ~|(addr ^ 8'h63);
    assign we_64 = we & ~|(addr ^ 8'h64);
    assign we_65 = we & ~|(addr ^ 8'h65);
    assign we_66 = we & ~|(addr ^ 8'h66);
    assign we_67 = we & ~|(addr ^ 8'h67);
    assign we_68 = we & ~|(addr ^ 8'h68);
    assign we_69 = we & ~|(addr ^ 8'h69);
    assign we_6A = we & ~|(addr ^ 8'h6A);
    assign we_6B = we & ~|(addr ^ 8'h6B);
    assign we_6C = we & ~|(addr ^ 8'h6C);
    assign we_6D = we & ~|(addr ^ 8'h6D);
    assign we_6E = we & ~|(addr ^ 8'h6E);
    assign we_6F = we & ~|(addr ^ 8'h6F);
    assign we_70 = we & ~|(addr ^ 8'h70);
    assign we_71 = we & ~|(addr ^ 8'h71);
    assign we_72 = we & ~|(addr ^ 8'h72);
    assign we_73 = we & ~|(addr ^ 8'h73);
    assign we_74 = we & ~|(addr ^ 8'h74);
    assign we_75 = we & ~|(addr ^ 8'h75);
    assign we_76 = we & ~|(addr ^ 8'h76);
    assign we_77 = we & ~|(addr ^ 8'h77);
    assign we_78 = we & ~|(addr ^ 8'h78);
    assign we_79 = we & ~|(addr ^ 8'h79);
    assign we_7A = we & ~|(addr ^ 8'h7A);
    assign we_7B = we & ~|(addr ^ 8'h7B);
    assign we_7C = we & ~|(addr ^ 8'h7C);
    assign we_7D = we & ~|(addr ^ 8'h7D);
    assign we_7E = we & ~|(addr ^ 8'h7E);
    assign we_7F = we & ~|(addr ^ 8'h7F);
    assign we_80 = we & ~|(addr ^ 8'h80);
    assign we_81 = we & ~|(addr ^ 8'h81);
    assign we_82 = we & ~|(addr ^ 8'h82);
    assign we_83 = we & ~|(addr ^ 8'h83);
    assign we_84 = we & ~|(addr ^ 8'h84);
    assign we_85 = we & ~|(addr ^ 8'h85);
    assign we_86 = we & ~|(addr ^ 8'h86);
    assign we_87 = we & ~|(addr ^ 8'h87);
    assign we_88 = we & ~|(addr ^ 8'h88);
    assign we_89 = we & ~|(addr ^ 8'h89);
    assign we_8A = we & ~|(addr ^ 8'h8A);
    assign we_8B = we & ~|(addr ^ 8'h8B);
    assign we_8C = we & ~|(addr ^ 8'h8C);
    assign we_8D = we & ~|(addr ^ 8'h8D);
    assign we_8E = we & ~|(addr ^ 8'h8E);
    assign we_8F = we & ~|(addr ^ 8'h8F);
    assign we_90 = we & ~|(addr ^ 8'h90);
    assign we_91 = we & ~|(addr ^ 8'h91);
    assign we_92 = we & ~|(addr ^ 8'h92);
    assign we_93 = we & ~|(addr ^ 8'h93);
    assign we_94 = we & ~|(addr ^ 8'h94);
    assign we_95 = we & ~|(addr ^ 8'h95);
    assign we_96 = we & ~|(addr ^ 8'h96);
    assign we_97 = we & ~|(addr ^ 8'h97);
    assign we_98 = we & ~|(addr ^ 8'h98);
    assign we_99 = we & ~|(addr ^ 8'h99);
    assign we_9A = we & ~|(addr ^ 8'h9A);
    assign we_9B = we & ~|(addr ^ 8'h9B);
    assign we_9C = we & ~|(addr ^ 8'h9C);
    assign we_9D = we & ~|(addr ^ 8'h9D);
    assign we_9E = we & ~|(addr ^ 8'h9E);
    assign we_9F = we & ~|(addr ^ 8'h9F);
    assign we_A0 = we & ~|(addr ^ 8'hA0);
    assign we_A1 = we & ~|(addr ^ 8'hA1);
    assign we_A2 = we & ~|(addr ^ 8'hA2);
    assign we_A3 = we & ~|(addr ^ 8'hA3);
    assign we_A4 = we & ~|(addr ^ 8'hA4);
    assign we_A5 = we & ~|(addr ^ 8'hA5);
    assign we_A6 = we & ~|(addr ^ 8'hA6);
    assign we_A7 = we & ~|(addr ^ 8'hA7);
    assign we_A8 = we & ~|(addr ^ 8'hA8);
    assign we_A9 = we & ~|(addr ^ 8'hA9);
    assign we_AA = we & ~|(addr ^ 8'hAA);
    assign we_AB = we & ~|(addr ^ 8'hAB);
    assign we_AC = we & ~|(addr ^ 8'hAC);
    assign we_AD = we & ~|(addr ^ 8'hAD);
    assign we_AE = we & ~|(addr ^ 8'hAE);
    assign we_AF = we & ~|(addr ^ 8'hAF);
    assign we_B0 = we & ~|(addr ^ 8'hB0);
    assign we_B1 = we & ~|(addr ^ 8'hB1);
    assign we_B2 = we & ~|(addr ^ 8'hB2);
    assign we_B3 = we & ~|(addr ^ 8'hB3);
    assign we_B4 = we & ~|(addr ^ 8'hB4);
    assign we_B5 = we & ~|(addr ^ 8'hB5);
    assign we_B6 = we & ~|(addr ^ 8'hB6);
    assign we_B7 = we & ~|(addr ^ 8'hB7);
    assign we_B8 = we & ~|(addr ^ 8'hB8);
    assign we_B9 = we & ~|(addr ^ 8'hB9);
    assign we_BA = we & ~|(addr ^ 8'hBA);
    assign we_BB = we & ~|(addr ^ 8'hBB);
    assign we_BC = we & ~|(addr ^ 8'hBC);
    assign we_BD = we & ~|(addr ^ 8'hBD);
    assign we_BE = we & ~|(addr ^ 8'hBE);
    assign we_BF = we & ~|(addr ^ 8'hBF);
    assign we_C0 = we & ~|(addr ^ 8'hC0);
    assign we_C1 = we & ~|(addr ^ 8'hC1);
    assign we_C2 = we & ~|(addr ^ 8'hC2);
    assign we_C3 = we & ~|(addr ^ 8'hC3);
    assign we_C4 = we & ~|(addr ^ 8'hC4);
    assign we_C5 = we & ~|(addr ^ 8'hC5);
    assign we_C6 = we & ~|(addr ^ 8'hC6);
    assign we_C7 = we & ~|(addr ^ 8'hC7);
    assign we_C8 = we & ~|(addr ^ 8'hC8);
    assign we_C9 = we & ~|(addr ^ 8'hC9);
    assign we_CA = we & ~|(addr ^ 8'hCA);
    assign we_CB = we & ~|(addr ^ 8'hCB);
    assign we_CC = we & ~|(addr ^ 8'hCC);
    assign we_CD = we & ~|(addr ^ 8'hCD);
    assign we_CE = we & ~|(addr ^ 8'hCE);
    assign we_CF = we & ~|(addr ^ 8'hCF);
    assign we_D0 = we & ~|(addr ^ 8'hD0);
    assign we_D1 = we & ~|(addr ^ 8'hD1);
    assign we_D2 = we & ~|(addr ^ 8'hD2);
    assign we_D3 = we & ~|(addr ^ 8'hD3);
    assign we_D4 = we & ~|(addr ^ 8'hD4);
    assign we_D5 = we & ~|(addr ^ 8'hD5);
    assign we_D6 = we & ~|(addr ^ 8'hD6);
    assign we_D7 = we & ~|(addr ^ 8'hD7);
    assign we_D8 = we & ~|(addr ^ 8'hD8);
    assign we_D9 = we & ~|(addr ^ 8'hD9);
    assign we_DA = we & ~|(addr ^ 8'hDA);
    assign we_DB = we & ~|(addr ^ 8'hDB);
    assign we_DC = we & ~|(addr ^ 8'hDC);
    assign we_DD = we & ~|(addr ^ 8'hDD);
    assign we_DE = we & ~|(addr ^ 8'hDE);
    assign we_DF = we & ~|(addr ^ 8'hDF);
    assign we_E0 = we & ~|(addr ^ 8'hE0);
    assign we_E1 = we & ~|(addr ^ 8'hE1);
    assign we_E2 = we & ~|(addr ^ 8'hE2);
    assign we_E3 = we & ~|(addr ^ 8'hE3);
    assign we_E4 = we & ~|(addr ^ 8'hE4);
    assign we_E5 = we & ~|(addr ^ 8'hE5);
    assign we_E6 = we & ~|(addr ^ 8'hE6);
    assign we_E7 = we & ~|(addr ^ 8'hE7);
    assign we_E8 = we & ~|(addr ^ 8'hE8);
    assign we_E9 = we & ~|(addr ^ 8'hE9);
    assign we_EA = we & ~|(addr ^ 8'hEA);
    assign we_EB = we & ~|(addr ^ 8'hEB);
    assign we_EC = we & ~|(addr ^ 8'hEC);
    assign we_ED = we & ~|(addr ^ 8'hED);
    assign we_EE = we & ~|(addr ^ 8'hEE);
    assign we_EF = we & ~|(addr ^ 8'hEF);
    assign we_F0 = we & ~|(addr ^ 8'hF0);
    assign we_F1 = we & ~|(addr ^ 8'hF1);
    assign we_F2 = we & ~|(addr ^ 8'hF2);
    assign we_F3 = we & ~|(addr ^ 8'hF3);
    assign we_F4 = we & ~|(addr ^ 8'hF4);
    assign we_F5 = we & ~|(addr ^ 8'hF5);
    assign we_F6 = we & ~|(addr ^ 8'hF6);
    assign we_F7 = we & ~|(addr ^ 8'hF7);
    assign we_F8 = we & ~|(addr ^ 8'hF8);
    assign we_F9 = we & ~|(addr ^ 8'hF9);
    assign we_FA = we & ~|(addr ^ 8'hFA);
    assign we_FB = we & ~|(addr ^ 8'hFB);
    assign we_FC = we & ~|(addr ^ 8'hFC);
    assign we_FD = we & ~|(addr ^ 8'hFD);
    assign we_FE = we & ~|(addr ^ 8'hFE);
    assign we_FF = we & ~|(addr ^ 8'hFF);

    // --- Physical Register Cells (256 Bytes / 2048 D-Flip-Flops) ---
    cpu_register #(.WIDTH(8)) cell_00 (
        .clk(clk), .rst(rst), .we(we_00), .data_in(data_in), .data_out(mem_out_00)
    );
    cpu_register #(.WIDTH(8)) cell_01 (
        .clk(clk), .rst(rst), .we(we_01), .data_in(data_in), .data_out(mem_out_01)
    );
    cpu_register #(.WIDTH(8)) cell_02 (
        .clk(clk), .rst(rst), .we(we_02), .data_in(data_in), .data_out(mem_out_02)
    );
    cpu_register #(.WIDTH(8)) cell_03 (
        .clk(clk), .rst(rst), .we(we_03), .data_in(data_in), .data_out(mem_out_03)
    );
    cpu_register #(.WIDTH(8)) cell_04 (
        .clk(clk), .rst(rst), .we(we_04), .data_in(data_in), .data_out(mem_out_04)
    );
    cpu_register #(.WIDTH(8)) cell_05 (
        .clk(clk), .rst(rst), .we(we_05), .data_in(data_in), .data_out(mem_out_05)
    );
    cpu_register #(.WIDTH(8)) cell_06 (
        .clk(clk), .rst(rst), .we(we_06), .data_in(data_in), .data_out(mem_out_06)
    );
    cpu_register #(.WIDTH(8)) cell_07 (
        .clk(clk), .rst(rst), .we(we_07), .data_in(data_in), .data_out(mem_out_07)
    );
    cpu_register #(.WIDTH(8)) cell_08 (
        .clk(clk), .rst(rst), .we(we_08), .data_in(data_in), .data_out(mem_out_08)
    );
    cpu_register #(.WIDTH(8)) cell_09 (
        .clk(clk), .rst(rst), .we(we_09), .data_in(data_in), .data_out(mem_out_09)
    );
    cpu_register #(.WIDTH(8)) cell_0A (
        .clk(clk), .rst(rst), .we(we_0A), .data_in(data_in), .data_out(mem_out_0A)
    );
    cpu_register #(.WIDTH(8)) cell_0B (
        .clk(clk), .rst(rst), .we(we_0B), .data_in(data_in), .data_out(mem_out_0B)
    );
    cpu_register #(.WIDTH(8)) cell_0C (
        .clk(clk), .rst(rst), .we(we_0C), .data_in(data_in), .data_out(mem_out_0C)
    );
    cpu_register #(.WIDTH(8)) cell_0D (
        .clk(clk), .rst(rst), .we(we_0D), .data_in(data_in), .data_out(mem_out_0D)
    );
    cpu_register #(.WIDTH(8)) cell_0E (
        .clk(clk), .rst(rst), .we(we_0E), .data_in(data_in), .data_out(mem_out_0E)
    );
    cpu_register #(.WIDTH(8)) cell_0F (
        .clk(clk), .rst(rst), .we(we_0F), .data_in(data_in), .data_out(mem_out_0F)
    );
    cpu_register #(.WIDTH(8)) cell_10 (
        .clk(clk), .rst(rst), .we(we_10), .data_in(data_in), .data_out(mem_out_10)
    );
    cpu_register #(.WIDTH(8)) cell_11 (
        .clk(clk), .rst(rst), .we(we_11), .data_in(data_in), .data_out(mem_out_11)
    );
    cpu_register #(.WIDTH(8)) cell_12 (
        .clk(clk), .rst(rst), .we(we_12), .data_in(data_in), .data_out(mem_out_12)
    );
    cpu_register #(.WIDTH(8)) cell_13 (
        .clk(clk), .rst(rst), .we(we_13), .data_in(data_in), .data_out(mem_out_13)
    );
    cpu_register #(.WIDTH(8)) cell_14 (
        .clk(clk), .rst(rst), .we(we_14), .data_in(data_in), .data_out(mem_out_14)
    );
    cpu_register #(.WIDTH(8)) cell_15 (
        .clk(clk), .rst(rst), .we(we_15), .data_in(data_in), .data_out(mem_out_15)
    );
    cpu_register #(.WIDTH(8)) cell_16 (
        .clk(clk), .rst(rst), .we(we_16), .data_in(data_in), .data_out(mem_out_16)
    );
    cpu_register #(.WIDTH(8)) cell_17 (
        .clk(clk), .rst(rst), .we(we_17), .data_in(data_in), .data_out(mem_out_17)
    );
    cpu_register #(.WIDTH(8)) cell_18 (
        .clk(clk), .rst(rst), .we(we_18), .data_in(data_in), .data_out(mem_out_18)
    );
    cpu_register #(.WIDTH(8)) cell_19 (
        .clk(clk), .rst(rst), .we(we_19), .data_in(data_in), .data_out(mem_out_19)
    );
    cpu_register #(.WIDTH(8)) cell_1A (
        .clk(clk), .rst(rst), .we(we_1A), .data_in(data_in), .data_out(mem_out_1A)
    );
    cpu_register #(.WIDTH(8)) cell_1B (
        .clk(clk), .rst(rst), .we(we_1B), .data_in(data_in), .data_out(mem_out_1B)
    );
    cpu_register #(.WIDTH(8)) cell_1C (
        .clk(clk), .rst(rst), .we(we_1C), .data_in(data_in), .data_out(mem_out_1C)
    );
    cpu_register #(.WIDTH(8)) cell_1D (
        .clk(clk), .rst(rst), .we(we_1D), .data_in(data_in), .data_out(mem_out_1D)
    );
    cpu_register #(.WIDTH(8)) cell_1E (
        .clk(clk), .rst(rst), .we(we_1E), .data_in(data_in), .data_out(mem_out_1E)
    );
    cpu_register #(.WIDTH(8)) cell_1F (
        .clk(clk), .rst(rst), .we(we_1F), .data_in(data_in), .data_out(mem_out_1F)
    );
    cpu_register #(.WIDTH(8)) cell_20 (
        .clk(clk), .rst(rst), .we(we_20), .data_in(data_in), .data_out(mem_out_20)
    );
    cpu_register #(.WIDTH(8)) cell_21 (
        .clk(clk), .rst(rst), .we(we_21), .data_in(data_in), .data_out(mem_out_21)
    );
    cpu_register #(.WIDTH(8)) cell_22 (
        .clk(clk), .rst(rst), .we(we_22), .data_in(data_in), .data_out(mem_out_22)
    );
    cpu_register #(.WIDTH(8)) cell_23 (
        .clk(clk), .rst(rst), .we(we_23), .data_in(data_in), .data_out(mem_out_23)
    );
    cpu_register #(.WIDTH(8)) cell_24 (
        .clk(clk), .rst(rst), .we(we_24), .data_in(data_in), .data_out(mem_out_24)
    );
    cpu_register #(.WIDTH(8)) cell_25 (
        .clk(clk), .rst(rst), .we(we_25), .data_in(data_in), .data_out(mem_out_25)
    );
    cpu_register #(.WIDTH(8)) cell_26 (
        .clk(clk), .rst(rst), .we(we_26), .data_in(data_in), .data_out(mem_out_26)
    );
    cpu_register #(.WIDTH(8)) cell_27 (
        .clk(clk), .rst(rst), .we(we_27), .data_in(data_in), .data_out(mem_out_27)
    );
    cpu_register #(.WIDTH(8)) cell_28 (
        .clk(clk), .rst(rst), .we(we_28), .data_in(data_in), .data_out(mem_out_28)
    );
    cpu_register #(.WIDTH(8)) cell_29 (
        .clk(clk), .rst(rst), .we(we_29), .data_in(data_in), .data_out(mem_out_29)
    );
    cpu_register #(.WIDTH(8)) cell_2A (
        .clk(clk), .rst(rst), .we(we_2A), .data_in(data_in), .data_out(mem_out_2A)
    );
    cpu_register #(.WIDTH(8)) cell_2B (
        .clk(clk), .rst(rst), .we(we_2B), .data_in(data_in), .data_out(mem_out_2B)
    );
    cpu_register #(.WIDTH(8)) cell_2C (
        .clk(clk), .rst(rst), .we(we_2C), .data_in(data_in), .data_out(mem_out_2C)
    );
    cpu_register #(.WIDTH(8)) cell_2D (
        .clk(clk), .rst(rst), .we(we_2D), .data_in(data_in), .data_out(mem_out_2D)
    );
    cpu_register #(.WIDTH(8)) cell_2E (
        .clk(clk), .rst(rst), .we(we_2E), .data_in(data_in), .data_out(mem_out_2E)
    );
    cpu_register #(.WIDTH(8)) cell_2F (
        .clk(clk), .rst(rst), .we(we_2F), .data_in(data_in), .data_out(mem_out_2F)
    );
    cpu_register #(.WIDTH(8)) cell_30 (
        .clk(clk), .rst(rst), .we(we_30), .data_in(data_in), .data_out(mem_out_30)
    );
    cpu_register #(.WIDTH(8)) cell_31 (
        .clk(clk), .rst(rst), .we(we_31), .data_in(data_in), .data_out(mem_out_31)
    );
    cpu_register #(.WIDTH(8)) cell_32 (
        .clk(clk), .rst(rst), .we(we_32), .data_in(data_in), .data_out(mem_out_32)
    );
    cpu_register #(.WIDTH(8)) cell_33 (
        .clk(clk), .rst(rst), .we(we_33), .data_in(data_in), .data_out(mem_out_33)
    );
    cpu_register #(.WIDTH(8)) cell_34 (
        .clk(clk), .rst(rst), .we(we_34), .data_in(data_in), .data_out(mem_out_34)
    );
    cpu_register #(.WIDTH(8)) cell_35 (
        .clk(clk), .rst(rst), .we(we_35), .data_in(data_in), .data_out(mem_out_35)
    );
    cpu_register #(.WIDTH(8)) cell_36 (
        .clk(clk), .rst(rst), .we(we_36), .data_in(data_in), .data_out(mem_out_36)
    );
    cpu_register #(.WIDTH(8)) cell_37 (
        .clk(clk), .rst(rst), .we(we_37), .data_in(data_in), .data_out(mem_out_37)
    );
    cpu_register #(.WIDTH(8)) cell_38 (
        .clk(clk), .rst(rst), .we(we_38), .data_in(data_in), .data_out(mem_out_38)
    );
    cpu_register #(.WIDTH(8)) cell_39 (
        .clk(clk), .rst(rst), .we(we_39), .data_in(data_in), .data_out(mem_out_39)
    );
    cpu_register #(.WIDTH(8)) cell_3A (
        .clk(clk), .rst(rst), .we(we_3A), .data_in(data_in), .data_out(mem_out_3A)
    );
    cpu_register #(.WIDTH(8)) cell_3B (
        .clk(clk), .rst(rst), .we(we_3B), .data_in(data_in), .data_out(mem_out_3B)
    );
    cpu_register #(.WIDTH(8)) cell_3C (
        .clk(clk), .rst(rst), .we(we_3C), .data_in(data_in), .data_out(mem_out_3C)
    );
    cpu_register #(.WIDTH(8)) cell_3D (
        .clk(clk), .rst(rst), .we(we_3D), .data_in(data_in), .data_out(mem_out_3D)
    );
    cpu_register #(.WIDTH(8)) cell_3E (
        .clk(clk), .rst(rst), .we(we_3E), .data_in(data_in), .data_out(mem_out_3E)
    );
    cpu_register #(.WIDTH(8)) cell_3F (
        .clk(clk), .rst(rst), .we(we_3F), .data_in(data_in), .data_out(mem_out_3F)
    );
    cpu_register #(.WIDTH(8)) cell_40 (
        .clk(clk), .rst(rst), .we(we_40), .data_in(data_in), .data_out(mem_out_40)
    );
    cpu_register #(.WIDTH(8)) cell_41 (
        .clk(clk), .rst(rst), .we(we_41), .data_in(data_in), .data_out(mem_out_41)
    );
    cpu_register #(.WIDTH(8)) cell_42 (
        .clk(clk), .rst(rst), .we(we_42), .data_in(data_in), .data_out(mem_out_42)
    );
    cpu_register #(.WIDTH(8)) cell_43 (
        .clk(clk), .rst(rst), .we(we_43), .data_in(data_in), .data_out(mem_out_43)
    );
    cpu_register #(.WIDTH(8)) cell_44 (
        .clk(clk), .rst(rst), .we(we_44), .data_in(data_in), .data_out(mem_out_44)
    );
    cpu_register #(.WIDTH(8)) cell_45 (
        .clk(clk), .rst(rst), .we(we_45), .data_in(data_in), .data_out(mem_out_45)
    );
    cpu_register #(.WIDTH(8)) cell_46 (
        .clk(clk), .rst(rst), .we(we_46), .data_in(data_in), .data_out(mem_out_46)
    );
    cpu_register #(.WIDTH(8)) cell_47 (
        .clk(clk), .rst(rst), .we(we_47), .data_in(data_in), .data_out(mem_out_47)
    );
    cpu_register #(.WIDTH(8)) cell_48 (
        .clk(clk), .rst(rst), .we(we_48), .data_in(data_in), .data_out(mem_out_48)
    );
    cpu_register #(.WIDTH(8)) cell_49 (
        .clk(clk), .rst(rst), .we(we_49), .data_in(data_in), .data_out(mem_out_49)
    );
    cpu_register #(.WIDTH(8)) cell_4A (
        .clk(clk), .rst(rst), .we(we_4A), .data_in(data_in), .data_out(mem_out_4A)
    );
    cpu_register #(.WIDTH(8)) cell_4B (
        .clk(clk), .rst(rst), .we(we_4B), .data_in(data_in), .data_out(mem_out_4B)
    );
    cpu_register #(.WIDTH(8)) cell_4C (
        .clk(clk), .rst(rst), .we(we_4C), .data_in(data_in), .data_out(mem_out_4C)
    );
    cpu_register #(.WIDTH(8)) cell_4D (
        .clk(clk), .rst(rst), .we(we_4D), .data_in(data_in), .data_out(mem_out_4D)
    );
    cpu_register #(.WIDTH(8)) cell_4E (
        .clk(clk), .rst(rst), .we(we_4E), .data_in(data_in), .data_out(mem_out_4E)
    );
    cpu_register #(.WIDTH(8)) cell_4F (
        .clk(clk), .rst(rst), .we(we_4F), .data_in(data_in), .data_out(mem_out_4F)
    );
    cpu_register #(.WIDTH(8)) cell_50 (
        .clk(clk), .rst(rst), .we(we_50), .data_in(data_in), .data_out(mem_out_50)
    );
    cpu_register #(.WIDTH(8)) cell_51 (
        .clk(clk), .rst(rst), .we(we_51), .data_in(data_in), .data_out(mem_out_51)
    );
    cpu_register #(.WIDTH(8)) cell_52 (
        .clk(clk), .rst(rst), .we(we_52), .data_in(data_in), .data_out(mem_out_52)
    );
    cpu_register #(.WIDTH(8)) cell_53 (
        .clk(clk), .rst(rst), .we(we_53), .data_in(data_in), .data_out(mem_out_53)
    );
    cpu_register #(.WIDTH(8)) cell_54 (
        .clk(clk), .rst(rst), .we(we_54), .data_in(data_in), .data_out(mem_out_54)
    );
    cpu_register #(.WIDTH(8)) cell_55 (
        .clk(clk), .rst(rst), .we(we_55), .data_in(data_in), .data_out(mem_out_55)
    );
    cpu_register #(.WIDTH(8)) cell_56 (
        .clk(clk), .rst(rst), .we(we_56), .data_in(data_in), .data_out(mem_out_56)
    );
    cpu_register #(.WIDTH(8)) cell_57 (
        .clk(clk), .rst(rst), .we(we_57), .data_in(data_in), .data_out(mem_out_57)
    );
    cpu_register #(.WIDTH(8)) cell_58 (
        .clk(clk), .rst(rst), .we(we_58), .data_in(data_in), .data_out(mem_out_58)
    );
    cpu_register #(.WIDTH(8)) cell_59 (
        .clk(clk), .rst(rst), .we(we_59), .data_in(data_in), .data_out(mem_out_59)
    );
    cpu_register #(.WIDTH(8)) cell_5A (
        .clk(clk), .rst(rst), .we(we_5A), .data_in(data_in), .data_out(mem_out_5A)
    );
    cpu_register #(.WIDTH(8)) cell_5B (
        .clk(clk), .rst(rst), .we(we_5B), .data_in(data_in), .data_out(mem_out_5B)
    );
    cpu_register #(.WIDTH(8)) cell_5C (
        .clk(clk), .rst(rst), .we(we_5C), .data_in(data_in), .data_out(mem_out_5C)
    );
    cpu_register #(.WIDTH(8)) cell_5D (
        .clk(clk), .rst(rst), .we(we_5D), .data_in(data_in), .data_out(mem_out_5D)
    );
    cpu_register #(.WIDTH(8)) cell_5E (
        .clk(clk), .rst(rst), .we(we_5E), .data_in(data_in), .data_out(mem_out_5E)
    );
    cpu_register #(.WIDTH(8)) cell_5F (
        .clk(clk), .rst(rst), .we(we_5F), .data_in(data_in), .data_out(mem_out_5F)
    );
    cpu_register #(.WIDTH(8)) cell_60 (
        .clk(clk), .rst(rst), .we(we_60), .data_in(data_in), .data_out(mem_out_60)
    );
    cpu_register #(.WIDTH(8)) cell_61 (
        .clk(clk), .rst(rst), .we(we_61), .data_in(data_in), .data_out(mem_out_61)
    );
    cpu_register #(.WIDTH(8)) cell_62 (
        .clk(clk), .rst(rst), .we(we_62), .data_in(data_in), .data_out(mem_out_62)
    );
    cpu_register #(.WIDTH(8)) cell_63 (
        .clk(clk), .rst(rst), .we(we_63), .data_in(data_in), .data_out(mem_out_63)
    );
    cpu_register #(.WIDTH(8)) cell_64 (
        .clk(clk), .rst(rst), .we(we_64), .data_in(data_in), .data_out(mem_out_64)
    );
    cpu_register #(.WIDTH(8)) cell_65 (
        .clk(clk), .rst(rst), .we(we_65), .data_in(data_in), .data_out(mem_out_65)
    );
    cpu_register #(.WIDTH(8)) cell_66 (
        .clk(clk), .rst(rst), .we(we_66), .data_in(data_in), .data_out(mem_out_66)
    );
    cpu_register #(.WIDTH(8)) cell_67 (
        .clk(clk), .rst(rst), .we(we_67), .data_in(data_in), .data_out(mem_out_67)
    );
    cpu_register #(.WIDTH(8)) cell_68 (
        .clk(clk), .rst(rst), .we(we_68), .data_in(data_in), .data_out(mem_out_68)
    );
    cpu_register #(.WIDTH(8)) cell_69 (
        .clk(clk), .rst(rst), .we(we_69), .data_in(data_in), .data_out(mem_out_69)
    );
    cpu_register #(.WIDTH(8)) cell_6A (
        .clk(clk), .rst(rst), .we(we_6A), .data_in(data_in), .data_out(mem_out_6A)
    );
    cpu_register #(.WIDTH(8)) cell_6B (
        .clk(clk), .rst(rst), .we(we_6B), .data_in(data_in), .data_out(mem_out_6B)
    );
    cpu_register #(.WIDTH(8)) cell_6C (
        .clk(clk), .rst(rst), .we(we_6C), .data_in(data_in), .data_out(mem_out_6C)
    );
    cpu_register #(.WIDTH(8)) cell_6D (
        .clk(clk), .rst(rst), .we(we_6D), .data_in(data_in), .data_out(mem_out_6D)
    );
    cpu_register #(.WIDTH(8)) cell_6E (
        .clk(clk), .rst(rst), .we(we_6E), .data_in(data_in), .data_out(mem_out_6E)
    );
    cpu_register #(.WIDTH(8)) cell_6F (
        .clk(clk), .rst(rst), .we(we_6F), .data_in(data_in), .data_out(mem_out_6F)
    );
    cpu_register #(.WIDTH(8)) cell_70 (
        .clk(clk), .rst(rst), .we(we_70), .data_in(data_in), .data_out(mem_out_70)
    );
    cpu_register #(.WIDTH(8)) cell_71 (
        .clk(clk), .rst(rst), .we(we_71), .data_in(data_in), .data_out(mem_out_71)
    );
    cpu_register #(.WIDTH(8)) cell_72 (
        .clk(clk), .rst(rst), .we(we_72), .data_in(data_in), .data_out(mem_out_72)
    );
    cpu_register #(.WIDTH(8)) cell_73 (
        .clk(clk), .rst(rst), .we(we_73), .data_in(data_in), .data_out(mem_out_73)
    );
    cpu_register #(.WIDTH(8)) cell_74 (
        .clk(clk), .rst(rst), .we(we_74), .data_in(data_in), .data_out(mem_out_74)
    );
    cpu_register #(.WIDTH(8)) cell_75 (
        .clk(clk), .rst(rst), .we(we_75), .data_in(data_in), .data_out(mem_out_75)
    );
    cpu_register #(.WIDTH(8)) cell_76 (
        .clk(clk), .rst(rst), .we(we_76), .data_in(data_in), .data_out(mem_out_76)
    );
    cpu_register #(.WIDTH(8)) cell_77 (
        .clk(clk), .rst(rst), .we(we_77), .data_in(data_in), .data_out(mem_out_77)
    );
    cpu_register #(.WIDTH(8)) cell_78 (
        .clk(clk), .rst(rst), .we(we_78), .data_in(data_in), .data_out(mem_out_78)
    );
    cpu_register #(.WIDTH(8)) cell_79 (
        .clk(clk), .rst(rst), .we(we_79), .data_in(data_in), .data_out(mem_out_79)
    );
    cpu_register #(.WIDTH(8)) cell_7A (
        .clk(clk), .rst(rst), .we(we_7A), .data_in(data_in), .data_out(mem_out_7A)
    );
    cpu_register #(.WIDTH(8)) cell_7B (
        .clk(clk), .rst(rst), .we(we_7B), .data_in(data_in), .data_out(mem_out_7B)
    );
    cpu_register #(.WIDTH(8)) cell_7C (
        .clk(clk), .rst(rst), .we(we_7C), .data_in(data_in), .data_out(mem_out_7C)
    );
    cpu_register #(.WIDTH(8)) cell_7D (
        .clk(clk), .rst(rst), .we(we_7D), .data_in(data_in), .data_out(mem_out_7D)
    );
    cpu_register #(.WIDTH(8)) cell_7E (
        .clk(clk), .rst(rst), .we(we_7E), .data_in(data_in), .data_out(mem_out_7E)
    );
    cpu_register #(.WIDTH(8)) cell_7F (
        .clk(clk), .rst(rst), .we(we_7F), .data_in(data_in), .data_out(mem_out_7F)
    );
    cpu_register #(.WIDTH(8)) cell_80 (
        .clk(clk), .rst(rst), .we(we_80), .data_in(data_in), .data_out(mem_out_80)
    );
    cpu_register #(.WIDTH(8)) cell_81 (
        .clk(clk), .rst(rst), .we(we_81), .data_in(data_in), .data_out(mem_out_81)
    );
    cpu_register #(.WIDTH(8)) cell_82 (
        .clk(clk), .rst(rst), .we(we_82), .data_in(data_in), .data_out(mem_out_82)
    );
    cpu_register #(.WIDTH(8)) cell_83 (
        .clk(clk), .rst(rst), .we(we_83), .data_in(data_in), .data_out(mem_out_83)
    );
    cpu_register #(.WIDTH(8)) cell_84 (
        .clk(clk), .rst(rst), .we(we_84), .data_in(data_in), .data_out(mem_out_84)
    );
    cpu_register #(.WIDTH(8)) cell_85 (
        .clk(clk), .rst(rst), .we(we_85), .data_in(data_in), .data_out(mem_out_85)
    );
    cpu_register #(.WIDTH(8)) cell_86 (
        .clk(clk), .rst(rst), .we(we_86), .data_in(data_in), .data_out(mem_out_86)
    );
    cpu_register #(.WIDTH(8)) cell_87 (
        .clk(clk), .rst(rst), .we(we_87), .data_in(data_in), .data_out(mem_out_87)
    );
    cpu_register #(.WIDTH(8)) cell_88 (
        .clk(clk), .rst(rst), .we(we_88), .data_in(data_in), .data_out(mem_out_88)
    );
    cpu_register #(.WIDTH(8)) cell_89 (
        .clk(clk), .rst(rst), .we(we_89), .data_in(data_in), .data_out(mem_out_89)
    );
    cpu_register #(.WIDTH(8)) cell_8A (
        .clk(clk), .rst(rst), .we(we_8A), .data_in(data_in), .data_out(mem_out_8A)
    );
    cpu_register #(.WIDTH(8)) cell_8B (
        .clk(clk), .rst(rst), .we(we_8B), .data_in(data_in), .data_out(mem_out_8B)
    );
    cpu_register #(.WIDTH(8)) cell_8C (
        .clk(clk), .rst(rst), .we(we_8C), .data_in(data_in), .data_out(mem_out_8C)
    );
    cpu_register #(.WIDTH(8)) cell_8D (
        .clk(clk), .rst(rst), .we(we_8D), .data_in(data_in), .data_out(mem_out_8D)
    );
    cpu_register #(.WIDTH(8)) cell_8E (
        .clk(clk), .rst(rst), .we(we_8E), .data_in(data_in), .data_out(mem_out_8E)
    );
    cpu_register #(.WIDTH(8)) cell_8F (
        .clk(clk), .rst(rst), .we(we_8F), .data_in(data_in), .data_out(mem_out_8F)
    );
    cpu_register #(.WIDTH(8)) cell_90 (
        .clk(clk), .rst(rst), .we(we_90), .data_in(data_in), .data_out(mem_out_90)
    );
    cpu_register #(.WIDTH(8)) cell_91 (
        .clk(clk), .rst(rst), .we(we_91), .data_in(data_in), .data_out(mem_out_91)
    );
    cpu_register #(.WIDTH(8)) cell_92 (
        .clk(clk), .rst(rst), .we(we_92), .data_in(data_in), .data_out(mem_out_92)
    );
    cpu_register #(.WIDTH(8)) cell_93 (
        .clk(clk), .rst(rst), .we(we_93), .data_in(data_in), .data_out(mem_out_93)
    );
    cpu_register #(.WIDTH(8)) cell_94 (
        .clk(clk), .rst(rst), .we(we_94), .data_in(data_in), .data_out(mem_out_94)
    );
    cpu_register #(.WIDTH(8)) cell_95 (
        .clk(clk), .rst(rst), .we(we_95), .data_in(data_in), .data_out(mem_out_95)
    );
    cpu_register #(.WIDTH(8)) cell_96 (
        .clk(clk), .rst(rst), .we(we_96), .data_in(data_in), .data_out(mem_out_96)
    );
    cpu_register #(.WIDTH(8)) cell_97 (
        .clk(clk), .rst(rst), .we(we_97), .data_in(data_in), .data_out(mem_out_97)
    );
    cpu_register #(.WIDTH(8)) cell_98 (
        .clk(clk), .rst(rst), .we(we_98), .data_in(data_in), .data_out(mem_out_98)
    );
    cpu_register #(.WIDTH(8)) cell_99 (
        .clk(clk), .rst(rst), .we(we_99), .data_in(data_in), .data_out(mem_out_99)
    );
    cpu_register #(.WIDTH(8)) cell_9A (
        .clk(clk), .rst(rst), .we(we_9A), .data_in(data_in), .data_out(mem_out_9A)
    );
    cpu_register #(.WIDTH(8)) cell_9B (
        .clk(clk), .rst(rst), .we(we_9B), .data_in(data_in), .data_out(mem_out_9B)
    );
    cpu_register #(.WIDTH(8)) cell_9C (
        .clk(clk), .rst(rst), .we(we_9C), .data_in(data_in), .data_out(mem_out_9C)
    );
    cpu_register #(.WIDTH(8)) cell_9D (
        .clk(clk), .rst(rst), .we(we_9D), .data_in(data_in), .data_out(mem_out_9D)
    );
    cpu_register #(.WIDTH(8)) cell_9E (
        .clk(clk), .rst(rst), .we(we_9E), .data_in(data_in), .data_out(mem_out_9E)
    );
    cpu_register #(.WIDTH(8)) cell_9F (
        .clk(clk), .rst(rst), .we(we_9F), .data_in(data_in), .data_out(mem_out_9F)
    );
    cpu_register #(.WIDTH(8)) cell_A0 (
        .clk(clk), .rst(rst), .we(we_A0), .data_in(data_in), .data_out(mem_out_A0)
    );
    cpu_register #(.WIDTH(8)) cell_A1 (
        .clk(clk), .rst(rst), .we(we_A1), .data_in(data_in), .data_out(mem_out_A1)
    );
    cpu_register #(.WIDTH(8)) cell_A2 (
        .clk(clk), .rst(rst), .we(we_A2), .data_in(data_in), .data_out(mem_out_A2)
    );
    cpu_register #(.WIDTH(8)) cell_A3 (
        .clk(clk), .rst(rst), .we(we_A3), .data_in(data_in), .data_out(mem_out_A3)
    );
    cpu_register #(.WIDTH(8)) cell_A4 (
        .clk(clk), .rst(rst), .we(we_A4), .data_in(data_in), .data_out(mem_out_A4)
    );
    cpu_register #(.WIDTH(8)) cell_A5 (
        .clk(clk), .rst(rst), .we(we_A5), .data_in(data_in), .data_out(mem_out_A5)
    );
    cpu_register #(.WIDTH(8)) cell_A6 (
        .clk(clk), .rst(rst), .we(we_A6), .data_in(data_in), .data_out(mem_out_A6)
    );
    cpu_register #(.WIDTH(8)) cell_A7 (
        .clk(clk), .rst(rst), .we(we_A7), .data_in(data_in), .data_out(mem_out_A7)
    );
    cpu_register #(.WIDTH(8)) cell_A8 (
        .clk(clk), .rst(rst), .we(we_A8), .data_in(data_in), .data_out(mem_out_A8)
    );
    cpu_register #(.WIDTH(8)) cell_A9 (
        .clk(clk), .rst(rst), .we(we_A9), .data_in(data_in), .data_out(mem_out_A9)
    );
    cpu_register #(.WIDTH(8)) cell_AA (
        .clk(clk), .rst(rst), .we(we_AA), .data_in(data_in), .data_out(mem_out_AA)
    );
    cpu_register #(.WIDTH(8)) cell_AB (
        .clk(clk), .rst(rst), .we(we_AB), .data_in(data_in), .data_out(mem_out_AB)
    );
    cpu_register #(.WIDTH(8)) cell_AC (
        .clk(clk), .rst(rst), .we(we_AC), .data_in(data_in), .data_out(mem_out_AC)
    );
    cpu_register #(.WIDTH(8)) cell_AD (
        .clk(clk), .rst(rst), .we(we_AD), .data_in(data_in), .data_out(mem_out_AD)
    );
    cpu_register #(.WIDTH(8)) cell_AE (
        .clk(clk), .rst(rst), .we(we_AE), .data_in(data_in), .data_out(mem_out_AE)
    );
    cpu_register #(.WIDTH(8)) cell_AF (
        .clk(clk), .rst(rst), .we(we_AF), .data_in(data_in), .data_out(mem_out_AF)
    );
    cpu_register #(.WIDTH(8)) cell_B0 (
        .clk(clk), .rst(rst), .we(we_B0), .data_in(data_in), .data_out(mem_out_B0)
    );
    cpu_register #(.WIDTH(8)) cell_B1 (
        .clk(clk), .rst(rst), .we(we_B1), .data_in(data_in), .data_out(mem_out_B1)
    );
    cpu_register #(.WIDTH(8)) cell_B2 (
        .clk(clk), .rst(rst), .we(we_B2), .data_in(data_in), .data_out(mem_out_B2)
    );
    cpu_register #(.WIDTH(8)) cell_B3 (
        .clk(clk), .rst(rst), .we(we_B3), .data_in(data_in), .data_out(mem_out_B3)
    );
    cpu_register #(.WIDTH(8)) cell_B4 (
        .clk(clk), .rst(rst), .we(we_B4), .data_in(data_in), .data_out(mem_out_B4)
    );
    cpu_register #(.WIDTH(8)) cell_B5 (
        .clk(clk), .rst(rst), .we(we_B5), .data_in(data_in), .data_out(mem_out_B5)
    );
    cpu_register #(.WIDTH(8)) cell_B6 (
        .clk(clk), .rst(rst), .we(we_B6), .data_in(data_in), .data_out(mem_out_B6)
    );
    cpu_register #(.WIDTH(8)) cell_B7 (
        .clk(clk), .rst(rst), .we(we_B7), .data_in(data_in), .data_out(mem_out_B7)
    );
    cpu_register #(.WIDTH(8)) cell_B8 (
        .clk(clk), .rst(rst), .we(we_B8), .data_in(data_in), .data_out(mem_out_B8)
    );
    cpu_register #(.WIDTH(8)) cell_B9 (
        .clk(clk), .rst(rst), .we(we_B9), .data_in(data_in), .data_out(mem_out_B9)
    );
    cpu_register #(.WIDTH(8)) cell_BA (
        .clk(clk), .rst(rst), .we(we_BA), .data_in(data_in), .data_out(mem_out_BA)
    );
    cpu_register #(.WIDTH(8)) cell_BB (
        .clk(clk), .rst(rst), .we(we_BB), .data_in(data_in), .data_out(mem_out_BB)
    );
    cpu_register #(.WIDTH(8)) cell_BC (
        .clk(clk), .rst(rst), .we(we_BC), .data_in(data_in), .data_out(mem_out_BC)
    );
    cpu_register #(.WIDTH(8)) cell_BD (
        .clk(clk), .rst(rst), .we(we_BD), .data_in(data_in), .data_out(mem_out_BD)
    );
    cpu_register #(.WIDTH(8)) cell_BE (
        .clk(clk), .rst(rst), .we(we_BE), .data_in(data_in), .data_out(mem_out_BE)
    );
    cpu_register #(.WIDTH(8)) cell_BF (
        .clk(clk), .rst(rst), .we(we_BF), .data_in(data_in), .data_out(mem_out_BF)
    );
    cpu_register #(.WIDTH(8)) cell_C0 (
        .clk(clk), .rst(rst), .we(we_C0), .data_in(data_in), .data_out(mem_out_C0)
    );
    cpu_register #(.WIDTH(8)) cell_C1 (
        .clk(clk), .rst(rst), .we(we_C1), .data_in(data_in), .data_out(mem_out_C1)
    );
    cpu_register #(.WIDTH(8)) cell_C2 (
        .clk(clk), .rst(rst), .we(we_C2), .data_in(data_in), .data_out(mem_out_C2)
    );
    cpu_register #(.WIDTH(8)) cell_C3 (
        .clk(clk), .rst(rst), .we(we_C3), .data_in(data_in), .data_out(mem_out_C3)
    );
    cpu_register #(.WIDTH(8)) cell_C4 (
        .clk(clk), .rst(rst), .we(we_C4), .data_in(data_in), .data_out(mem_out_C4)
    );
    cpu_register #(.WIDTH(8)) cell_C5 (
        .clk(clk), .rst(rst), .we(we_C5), .data_in(data_in), .data_out(mem_out_C5)
    );
    cpu_register #(.WIDTH(8)) cell_C6 (
        .clk(clk), .rst(rst), .we(we_C6), .data_in(data_in), .data_out(mem_out_C6)
    );
    cpu_register #(.WIDTH(8)) cell_C7 (
        .clk(clk), .rst(rst), .we(we_C7), .data_in(data_in), .data_out(mem_out_C7)
    );
    cpu_register #(.WIDTH(8)) cell_C8 (
        .clk(clk), .rst(rst), .we(we_C8), .data_in(data_in), .data_out(mem_out_C8)
    );
    cpu_register #(.WIDTH(8)) cell_C9 (
        .clk(clk), .rst(rst), .we(we_C9), .data_in(data_in), .data_out(mem_out_C9)
    );
    cpu_register #(.WIDTH(8)) cell_CA (
        .clk(clk), .rst(rst), .we(we_CA), .data_in(data_in), .data_out(mem_out_CA)
    );
    cpu_register #(.WIDTH(8)) cell_CB (
        .clk(clk), .rst(rst), .we(we_CB), .data_in(data_in), .data_out(mem_out_CB)
    );
    cpu_register #(.WIDTH(8)) cell_CC (
        .clk(clk), .rst(rst), .we(we_CC), .data_in(data_in), .data_out(mem_out_CC)
    );
    cpu_register #(.WIDTH(8)) cell_CD (
        .clk(clk), .rst(rst), .we(we_CD), .data_in(data_in), .data_out(mem_out_CD)
    );
    cpu_register #(.WIDTH(8)) cell_CE (
        .clk(clk), .rst(rst), .we(we_CE), .data_in(data_in), .data_out(mem_out_CE)
    );
    cpu_register #(.WIDTH(8)) cell_CF (
        .clk(clk), .rst(rst), .we(we_CF), .data_in(data_in), .data_out(mem_out_CF)
    );
    cpu_register #(.WIDTH(8)) cell_D0 (
        .clk(clk), .rst(rst), .we(we_D0), .data_in(data_in), .data_out(mem_out_D0)
    );
    cpu_register #(.WIDTH(8)) cell_D1 (
        .clk(clk), .rst(rst), .we(we_D1), .data_in(data_in), .data_out(mem_out_D1)
    );
    cpu_register #(.WIDTH(8)) cell_D2 (
        .clk(clk), .rst(rst), .we(we_D2), .data_in(data_in), .data_out(mem_out_D2)
    );
    cpu_register #(.WIDTH(8)) cell_D3 (
        .clk(clk), .rst(rst), .we(we_D3), .data_in(data_in), .data_out(mem_out_D3)
    );
    cpu_register #(.WIDTH(8)) cell_D4 (
        .clk(clk), .rst(rst), .we(we_D4), .data_in(data_in), .data_out(mem_out_D4)
    );
    cpu_register #(.WIDTH(8)) cell_D5 (
        .clk(clk), .rst(rst), .we(we_D5), .data_in(data_in), .data_out(mem_out_D5)
    );
    cpu_register #(.WIDTH(8)) cell_D6 (
        .clk(clk), .rst(rst), .we(we_D6), .data_in(data_in), .data_out(mem_out_D6)
    );
    cpu_register #(.WIDTH(8)) cell_D7 (
        .clk(clk), .rst(rst), .we(we_D7), .data_in(data_in), .data_out(mem_out_D7)
    );
    cpu_register #(.WIDTH(8)) cell_D8 (
        .clk(clk), .rst(rst), .we(we_D8), .data_in(data_in), .data_out(mem_out_D8)
    );
    cpu_register #(.WIDTH(8)) cell_D9 (
        .clk(clk), .rst(rst), .we(we_D9), .data_in(data_in), .data_out(mem_out_D9)
    );
    cpu_register #(.WIDTH(8)) cell_DA (
        .clk(clk), .rst(rst), .we(we_DA), .data_in(data_in), .data_out(mem_out_DA)
    );
    cpu_register #(.WIDTH(8)) cell_DB (
        .clk(clk), .rst(rst), .we(we_DB), .data_in(data_in), .data_out(mem_out_DB)
    );
    cpu_register #(.WIDTH(8)) cell_DC (
        .clk(clk), .rst(rst), .we(we_DC), .data_in(data_in), .data_out(mem_out_DC)
    );
    cpu_register #(.WIDTH(8)) cell_DD (
        .clk(clk), .rst(rst), .we(we_DD), .data_in(data_in), .data_out(mem_out_DD)
    );
    cpu_register #(.WIDTH(8)) cell_DE (
        .clk(clk), .rst(rst), .we(we_DE), .data_in(data_in), .data_out(mem_out_DE)
    );
    cpu_register #(.WIDTH(8)) cell_DF (
        .clk(clk), .rst(rst), .we(we_DF), .data_in(data_in), .data_out(mem_out_DF)
    );
    cpu_register #(.WIDTH(8)) cell_E0 (
        .clk(clk), .rst(rst), .we(we_E0), .data_in(data_in), .data_out(mem_out_E0)
    );
    cpu_register #(.WIDTH(8)) cell_E1 (
        .clk(clk), .rst(rst), .we(we_E1), .data_in(data_in), .data_out(mem_out_E1)
    );
    cpu_register #(.WIDTH(8)) cell_E2 (
        .clk(clk), .rst(rst), .we(we_E2), .data_in(data_in), .data_out(mem_out_E2)
    );
    cpu_register #(.WIDTH(8)) cell_E3 (
        .clk(clk), .rst(rst), .we(we_E3), .data_in(data_in), .data_out(mem_out_E3)
    );
    cpu_register #(.WIDTH(8)) cell_E4 (
        .clk(clk), .rst(rst), .we(we_E4), .data_in(data_in), .data_out(mem_out_E4)
    );
    cpu_register #(.WIDTH(8)) cell_E5 (
        .clk(clk), .rst(rst), .we(we_E5), .data_in(data_in), .data_out(mem_out_E5)
    );
    cpu_register #(.WIDTH(8)) cell_E6 (
        .clk(clk), .rst(rst), .we(we_E6), .data_in(data_in), .data_out(mem_out_E6)
    );
    cpu_register #(.WIDTH(8)) cell_E7 (
        .clk(clk), .rst(rst), .we(we_E7), .data_in(data_in), .data_out(mem_out_E7)
    );
    cpu_register #(.WIDTH(8)) cell_E8 (
        .clk(clk), .rst(rst), .we(we_E8), .data_in(data_in), .data_out(mem_out_E8)
    );
    cpu_register #(.WIDTH(8)) cell_E9 (
        .clk(clk), .rst(rst), .we(we_E9), .data_in(data_in), .data_out(mem_out_E9)
    );
    cpu_register #(.WIDTH(8)) cell_EA (
        .clk(clk), .rst(rst), .we(we_EA), .data_in(data_in), .data_out(mem_out_EA)
    );
    cpu_register #(.WIDTH(8)) cell_EB (
        .clk(clk), .rst(rst), .we(we_EB), .data_in(data_in), .data_out(mem_out_EB)
    );
    cpu_register #(.WIDTH(8)) cell_EC (
        .clk(clk), .rst(rst), .we(we_EC), .data_in(data_in), .data_out(mem_out_EC)
    );
    cpu_register #(.WIDTH(8)) cell_ED (
        .clk(clk), .rst(rst), .we(we_ED), .data_in(data_in), .data_out(mem_out_ED)
    );
    cpu_register #(.WIDTH(8)) cell_EE (
        .clk(clk), .rst(rst), .we(we_EE), .data_in(data_in), .data_out(mem_out_EE)
    );
    cpu_register #(.WIDTH(8)) cell_EF (
        .clk(clk), .rst(rst), .we(we_EF), .data_in(data_in), .data_out(mem_out_EF)
    );
    cpu_register #(.WIDTH(8)) cell_F0 (
        .clk(clk), .rst(rst), .we(we_F0), .data_in(data_in), .data_out(mem_out_F0)
    );
    cpu_register #(.WIDTH(8)) cell_F1 (
        .clk(clk), .rst(rst), .we(we_F1), .data_in(data_in), .data_out(mem_out_F1)
    );
    cpu_register #(.WIDTH(8)) cell_F2 (
        .clk(clk), .rst(rst), .we(we_F2), .data_in(data_in), .data_out(mem_out_F2)
    );
    cpu_register #(.WIDTH(8)) cell_F3 (
        .clk(clk), .rst(rst), .we(we_F3), .data_in(data_in), .data_out(mem_out_F3)
    );
    cpu_register #(.WIDTH(8)) cell_F4 (
        .clk(clk), .rst(rst), .we(we_F4), .data_in(data_in), .data_out(mem_out_F4)
    );
    cpu_register #(.WIDTH(8)) cell_F5 (
        .clk(clk), .rst(rst), .we(we_F5), .data_in(data_in), .data_out(mem_out_F5)
    );
    cpu_register #(.WIDTH(8)) cell_F6 (
        .clk(clk), .rst(rst), .we(we_F6), .data_in(data_in), .data_out(mem_out_F6)
    );
    cpu_register #(.WIDTH(8)) cell_F7 (
        .clk(clk), .rst(rst), .we(we_F7), .data_in(data_in), .data_out(mem_out_F7)
    );
    cpu_register #(.WIDTH(8)) cell_F8 (
        .clk(clk), .rst(rst), .we(we_F8), .data_in(data_in), .data_out(mem_out_F8)
    );
    cpu_register #(.WIDTH(8)) cell_F9 (
        .clk(clk), .rst(rst), .we(we_F9), .data_in(data_in), .data_out(mem_out_F9)
    );
    cpu_register #(.WIDTH(8)) cell_FA (
        .clk(clk), .rst(rst), .we(we_FA), .data_in(data_in), .data_out(mem_out_FA)
    );
    cpu_register #(.WIDTH(8)) cell_FB (
        .clk(clk), .rst(rst), .we(we_FB), .data_in(data_in), .data_out(mem_out_FB)
    );
    cpu_register #(.WIDTH(8)) cell_FC (
        .clk(clk), .rst(rst), .we(we_FC), .data_in(data_in), .data_out(mem_out_FC)
    );
    cpu_register #(.WIDTH(8)) cell_FD (
        .clk(clk), .rst(rst), .we(we_FD), .data_in(data_in), .data_out(mem_out_FD)
    );
    cpu_register #(.WIDTH(8)) cell_FE (
        .clk(clk), .rst(rst), .we(we_FE), .data_in(data_in), .data_out(mem_out_FE)
    );
    cpu_register #(.WIDTH(8)) cell_FF (
        .clk(clk), .rst(rst), .we(we_FF), .data_in(data_in), .data_out(mem_out_FF)
    );

    // --- Read Multiplexer (256-to-1 MUX) ---
    assign data_out =
        ({8{~|(addr ^ 8'h00)}} & mem_out_00) |
        ({8{~|(addr ^ 8'h01)}} & mem_out_01) |
        ({8{~|(addr ^ 8'h02)}} & mem_out_02) |
        ({8{~|(addr ^ 8'h03)}} & mem_out_03) |
        ({8{~|(addr ^ 8'h04)}} & mem_out_04) |
        ({8{~|(addr ^ 8'h05)}} & mem_out_05) |
        ({8{~|(addr ^ 8'h06)}} & mem_out_06) |
        ({8{~|(addr ^ 8'h07)}} & mem_out_07) |
        ({8{~|(addr ^ 8'h08)}} & mem_out_08) |
        ({8{~|(addr ^ 8'h09)}} & mem_out_09) |
        ({8{~|(addr ^ 8'h0A)}} & mem_out_0A) |
        ({8{~|(addr ^ 8'h0B)}} & mem_out_0B) |
        ({8{~|(addr ^ 8'h0C)}} & mem_out_0C) |
        ({8{~|(addr ^ 8'h0D)}} & mem_out_0D) |
        ({8{~|(addr ^ 8'h0E)}} & mem_out_0E) |
        ({8{~|(addr ^ 8'h0F)}} & mem_out_0F) |
        ({8{~|(addr ^ 8'h10)}} & mem_out_10) |
        ({8{~|(addr ^ 8'h11)}} & mem_out_11) |
        ({8{~|(addr ^ 8'h12)}} & mem_out_12) |
        ({8{~|(addr ^ 8'h13)}} & mem_out_13) |
        ({8{~|(addr ^ 8'h14)}} & mem_out_14) |
        ({8{~|(addr ^ 8'h15)}} & mem_out_15) |
        ({8{~|(addr ^ 8'h16)}} & mem_out_16) |
        ({8{~|(addr ^ 8'h17)}} & mem_out_17) |
        ({8{~|(addr ^ 8'h18)}} & mem_out_18) |
        ({8{~|(addr ^ 8'h19)}} & mem_out_19) |
        ({8{~|(addr ^ 8'h1A)}} & mem_out_1A) |
        ({8{~|(addr ^ 8'h1B)}} & mem_out_1B) |
        ({8{~|(addr ^ 8'h1C)}} & mem_out_1C) |
        ({8{~|(addr ^ 8'h1D)}} & mem_out_1D) |
        ({8{~|(addr ^ 8'h1E)}} & mem_out_1E) |
        ({8{~|(addr ^ 8'h1F)}} & mem_out_1F) |
        ({8{~|(addr ^ 8'h20)}} & mem_out_20) |
        ({8{~|(addr ^ 8'h21)}} & mem_out_21) |
        ({8{~|(addr ^ 8'h22)}} & mem_out_22) |
        ({8{~|(addr ^ 8'h23)}} & mem_out_23) |
        ({8{~|(addr ^ 8'h24)}} & mem_out_24) |
        ({8{~|(addr ^ 8'h25)}} & mem_out_25) |
        ({8{~|(addr ^ 8'h26)}} & mem_out_26) |
        ({8{~|(addr ^ 8'h27)}} & mem_out_27) |
        ({8{~|(addr ^ 8'h28)}} & mem_out_28) |
        ({8{~|(addr ^ 8'h29)}} & mem_out_29) |
        ({8{~|(addr ^ 8'h2A)}} & mem_out_2A) |
        ({8{~|(addr ^ 8'h2B)}} & mem_out_2B) |
        ({8{~|(addr ^ 8'h2C)}} & mem_out_2C) |
        ({8{~|(addr ^ 8'h2D)}} & mem_out_2D) |
        ({8{~|(addr ^ 8'h2E)}} & mem_out_2E) |
        ({8{~|(addr ^ 8'h2F)}} & mem_out_2F) |
        ({8{~|(addr ^ 8'h30)}} & mem_out_30) |
        ({8{~|(addr ^ 8'h31)}} & mem_out_31) |
        ({8{~|(addr ^ 8'h32)}} & mem_out_32) |
        ({8{~|(addr ^ 8'h33)}} & mem_out_33) |
        ({8{~|(addr ^ 8'h34)}} & mem_out_34) |
        ({8{~|(addr ^ 8'h35)}} & mem_out_35) |
        ({8{~|(addr ^ 8'h36)}} & mem_out_36) |
        ({8{~|(addr ^ 8'h37)}} & mem_out_37) |
        ({8{~|(addr ^ 8'h38)}} & mem_out_38) |
        ({8{~|(addr ^ 8'h39)}} & mem_out_39) |
        ({8{~|(addr ^ 8'h3A)}} & mem_out_3A) |
        ({8{~|(addr ^ 8'h3B)}} & mem_out_3B) |
        ({8{~|(addr ^ 8'h3C)}} & mem_out_3C) |
        ({8{~|(addr ^ 8'h3D)}} & mem_out_3D) |
        ({8{~|(addr ^ 8'h3E)}} & mem_out_3E) |
        ({8{~|(addr ^ 8'h3F)}} & mem_out_3F) |
        ({8{~|(addr ^ 8'h40)}} & mem_out_40) |
        ({8{~|(addr ^ 8'h41)}} & mem_out_41) |
        ({8{~|(addr ^ 8'h42)}} & mem_out_42) |
        ({8{~|(addr ^ 8'h43)}} & mem_out_43) |
        ({8{~|(addr ^ 8'h44)}} & mem_out_44) |
        ({8{~|(addr ^ 8'h45)}} & mem_out_45) |
        ({8{~|(addr ^ 8'h46)}} & mem_out_46) |
        ({8{~|(addr ^ 8'h47)}} & mem_out_47) |
        ({8{~|(addr ^ 8'h48)}} & mem_out_48) |
        ({8{~|(addr ^ 8'h49)}} & mem_out_49) |
        ({8{~|(addr ^ 8'h4A)}} & mem_out_4A) |
        ({8{~|(addr ^ 8'h4B)}} & mem_out_4B) |
        ({8{~|(addr ^ 8'h4C)}} & mem_out_4C) |
        ({8{~|(addr ^ 8'h4D)}} & mem_out_4D) |
        ({8{~|(addr ^ 8'h4E)}} & mem_out_4E) |
        ({8{~|(addr ^ 8'h4F)}} & mem_out_4F) |
        ({8{~|(addr ^ 8'h50)}} & mem_out_50) |
        ({8{~|(addr ^ 8'h51)}} & mem_out_51) |
        ({8{~|(addr ^ 8'h52)}} & mem_out_52) |
        ({8{~|(addr ^ 8'h53)}} & mem_out_53) |
        ({8{~|(addr ^ 8'h54)}} & mem_out_54) |
        ({8{~|(addr ^ 8'h55)}} & mem_out_55) |
        ({8{~|(addr ^ 8'h56)}} & mem_out_56) |
        ({8{~|(addr ^ 8'h57)}} & mem_out_57) |
        ({8{~|(addr ^ 8'h58)}} & mem_out_58) |
        ({8{~|(addr ^ 8'h59)}} & mem_out_59) |
        ({8{~|(addr ^ 8'h5A)}} & mem_out_5A) |
        ({8{~|(addr ^ 8'h5B)}} & mem_out_5B) |
        ({8{~|(addr ^ 8'h5C)}} & mem_out_5C) |
        ({8{~|(addr ^ 8'h5D)}} & mem_out_5D) |
        ({8{~|(addr ^ 8'h5E)}} & mem_out_5E) |
        ({8{~|(addr ^ 8'h5F)}} & mem_out_5F) |
        ({8{~|(addr ^ 8'h60)}} & mem_out_60) |
        ({8{~|(addr ^ 8'h61)}} & mem_out_61) |
        ({8{~|(addr ^ 8'h62)}} & mem_out_62) |
        ({8{~|(addr ^ 8'h63)}} & mem_out_63) |
        ({8{~|(addr ^ 8'h64)}} & mem_out_64) |
        ({8{~|(addr ^ 8'h65)}} & mem_out_65) |
        ({8{~|(addr ^ 8'h66)}} & mem_out_66) |
        ({8{~|(addr ^ 8'h67)}} & mem_out_67) |
        ({8{~|(addr ^ 8'h68)}} & mem_out_68) |
        ({8{~|(addr ^ 8'h69)}} & mem_out_69) |
        ({8{~|(addr ^ 8'h6A)}} & mem_out_6A) |
        ({8{~|(addr ^ 8'h6B)}} & mem_out_6B) |
        ({8{~|(addr ^ 8'h6C)}} & mem_out_6C) |
        ({8{~|(addr ^ 8'h6D)}} & mem_out_6D) |
        ({8{~|(addr ^ 8'h6E)}} & mem_out_6E) |
        ({8{~|(addr ^ 8'h6F)}} & mem_out_6F) |
        ({8{~|(addr ^ 8'h70)}} & mem_out_70) |
        ({8{~|(addr ^ 8'h71)}} & mem_out_71) |
        ({8{~|(addr ^ 8'h72)}} & mem_out_72) |
        ({8{~|(addr ^ 8'h73)}} & mem_out_73) |
        ({8{~|(addr ^ 8'h74)}} & mem_out_74) |
        ({8{~|(addr ^ 8'h75)}} & mem_out_75) |
        ({8{~|(addr ^ 8'h76)}} & mem_out_76) |
        ({8{~|(addr ^ 8'h77)}} & mem_out_77) |
        ({8{~|(addr ^ 8'h78)}} & mem_out_78) |
        ({8{~|(addr ^ 8'h79)}} & mem_out_79) |
        ({8{~|(addr ^ 8'h7A)}} & mem_out_7A) |
        ({8{~|(addr ^ 8'h7B)}} & mem_out_7B) |
        ({8{~|(addr ^ 8'h7C)}} & mem_out_7C) |
        ({8{~|(addr ^ 8'h7D)}} & mem_out_7D) |
        ({8{~|(addr ^ 8'h7E)}} & mem_out_7E) |
        ({8{~|(addr ^ 8'h7F)}} & mem_out_7F) |
        ({8{~|(addr ^ 8'h80)}} & mem_out_80) |
        ({8{~|(addr ^ 8'h81)}} & mem_out_81) |
        ({8{~|(addr ^ 8'h82)}} & mem_out_82) |
        ({8{~|(addr ^ 8'h83)}} & mem_out_83) |
        ({8{~|(addr ^ 8'h84)}} & mem_out_84) |
        ({8{~|(addr ^ 8'h85)}} & mem_out_85) |
        ({8{~|(addr ^ 8'h86)}} & mem_out_86) |
        ({8{~|(addr ^ 8'h87)}} & mem_out_87) |
        ({8{~|(addr ^ 8'h88)}} & mem_out_88) |
        ({8{~|(addr ^ 8'h89)}} & mem_out_89) |
        ({8{~|(addr ^ 8'h8A)}} & mem_out_8A) |
        ({8{~|(addr ^ 8'h8B)}} & mem_out_8B) |
        ({8{~|(addr ^ 8'h8C)}} & mem_out_8C) |
        ({8{~|(addr ^ 8'h8D)}} & mem_out_8D) |
        ({8{~|(addr ^ 8'h8E)}} & mem_out_8E) |
        ({8{~|(addr ^ 8'h8F)}} & mem_out_8F) |
        ({8{~|(addr ^ 8'h90)}} & mem_out_90) |
        ({8{~|(addr ^ 8'h91)}} & mem_out_91) |
        ({8{~|(addr ^ 8'h92)}} & mem_out_92) |
        ({8{~|(addr ^ 8'h93)}} & mem_out_93) |
        ({8{~|(addr ^ 8'h94)}} & mem_out_94) |
        ({8{~|(addr ^ 8'h95)}} & mem_out_95) |
        ({8{~|(addr ^ 8'h96)}} & mem_out_96) |
        ({8{~|(addr ^ 8'h97)}} & mem_out_97) |
        ({8{~|(addr ^ 8'h98)}} & mem_out_98) |
        ({8{~|(addr ^ 8'h99)}} & mem_out_99) |
        ({8{~|(addr ^ 8'h9A)}} & mem_out_9A) |
        ({8{~|(addr ^ 8'h9B)}} & mem_out_9B) |
        ({8{~|(addr ^ 8'h9C)}} & mem_out_9C) |
        ({8{~|(addr ^ 8'h9D)}} & mem_out_9D) |
        ({8{~|(addr ^ 8'h9E)}} & mem_out_9E) |
        ({8{~|(addr ^ 8'h9F)}} & mem_out_9F) |
        ({8{~|(addr ^ 8'hA0)}} & mem_out_A0) |
        ({8{~|(addr ^ 8'hA1)}} & mem_out_A1) |
        ({8{~|(addr ^ 8'hA2)}} & mem_out_A2) |
        ({8{~|(addr ^ 8'hA3)}} & mem_out_A3) |
        ({8{~|(addr ^ 8'hA4)}} & mem_out_A4) |
        ({8{~|(addr ^ 8'hA5)}} & mem_out_A5) |
        ({8{~|(addr ^ 8'hA6)}} & mem_out_A6) |
        ({8{~|(addr ^ 8'hA7)}} & mem_out_A7) |
        ({8{~|(addr ^ 8'hA8)}} & mem_out_A8) |
        ({8{~|(addr ^ 8'hA9)}} & mem_out_A9) |
        ({8{~|(addr ^ 8'hAA)}} & mem_out_AA) |
        ({8{~|(addr ^ 8'hAB)}} & mem_out_AB) |
        ({8{~|(addr ^ 8'hAC)}} & mem_out_AC) |
        ({8{~|(addr ^ 8'hAD)}} & mem_out_AD) |
        ({8{~|(addr ^ 8'hAE)}} & mem_out_AE) |
        ({8{~|(addr ^ 8'hAF)}} & mem_out_AF) |
        ({8{~|(addr ^ 8'hB0)}} & mem_out_B0) |
        ({8{~|(addr ^ 8'hB1)}} & mem_out_B1) |
        ({8{~|(addr ^ 8'hB2)}} & mem_out_B2) |
        ({8{~|(addr ^ 8'hB3)}} & mem_out_B3) |
        ({8{~|(addr ^ 8'hB4)}} & mem_out_B4) |
        ({8{~|(addr ^ 8'hB5)}} & mem_out_B5) |
        ({8{~|(addr ^ 8'hB6)}} & mem_out_B6) |
        ({8{~|(addr ^ 8'hB7)}} & mem_out_B7) |
        ({8{~|(addr ^ 8'hB8)}} & mem_out_B8) |
        ({8{~|(addr ^ 8'hB9)}} & mem_out_B9) |
        ({8{~|(addr ^ 8'hBA)}} & mem_out_BA) |
        ({8{~|(addr ^ 8'hBB)}} & mem_out_BB) |
        ({8{~|(addr ^ 8'hBC)}} & mem_out_BC) |
        ({8{~|(addr ^ 8'hBD)}} & mem_out_BD) |
        ({8{~|(addr ^ 8'hBE)}} & mem_out_BE) |
        ({8{~|(addr ^ 8'hBF)}} & mem_out_BF) |
        ({8{~|(addr ^ 8'hC0)}} & mem_out_C0) |
        ({8{~|(addr ^ 8'hC1)}} & mem_out_C1) |
        ({8{~|(addr ^ 8'hC2)}} & mem_out_C2) |
        ({8{~|(addr ^ 8'hC3)}} & mem_out_C3) |
        ({8{~|(addr ^ 8'hC4)}} & mem_out_C4) |
        ({8{~|(addr ^ 8'hC5)}} & mem_out_C5) |
        ({8{~|(addr ^ 8'hC6)}} & mem_out_C6) |
        ({8{~|(addr ^ 8'hC7)}} & mem_out_C7) |
        ({8{~|(addr ^ 8'hC8)}} & mem_out_C8) |
        ({8{~|(addr ^ 8'hC9)}} & mem_out_C9) |
        ({8{~|(addr ^ 8'hCA)}} & mem_out_CA) |
        ({8{~|(addr ^ 8'hCB)}} & mem_out_CB) |
        ({8{~|(addr ^ 8'hCC)}} & mem_out_CC) |
        ({8{~|(addr ^ 8'hCD)}} & mem_out_CD) |
        ({8{~|(addr ^ 8'hCE)}} & mem_out_CE) |
        ({8{~|(addr ^ 8'hCF)}} & mem_out_CF) |
        ({8{~|(addr ^ 8'hD0)}} & mem_out_D0) |
        ({8{~|(addr ^ 8'hD1)}} & mem_out_D1) |
        ({8{~|(addr ^ 8'hD2)}} & mem_out_D2) |
        ({8{~|(addr ^ 8'hD3)}} & mem_out_D3) |
        ({8{~|(addr ^ 8'hD4)}} & mem_out_D4) |
        ({8{~|(addr ^ 8'hD5)}} & mem_out_D5) |
        ({8{~|(addr ^ 8'hD6)}} & mem_out_D6) |
        ({8{~|(addr ^ 8'hD7)}} & mem_out_D7) |
        ({8{~|(addr ^ 8'hD8)}} & mem_out_D8) |
        ({8{~|(addr ^ 8'hD9)}} & mem_out_D9) |
        ({8{~|(addr ^ 8'hDA)}} & mem_out_DA) |
        ({8{~|(addr ^ 8'hDB)}} & mem_out_DB) |
        ({8{~|(addr ^ 8'hDC)}} & mem_out_DC) |
        ({8{~|(addr ^ 8'hDD)}} & mem_out_DD) |
        ({8{~|(addr ^ 8'hDE)}} & mem_out_DE) |
        ({8{~|(addr ^ 8'hDF)}} & mem_out_DF) |
        ({8{~|(addr ^ 8'hE0)}} & mem_out_E0) |
        ({8{~|(addr ^ 8'hE1)}} & mem_out_E1) |
        ({8{~|(addr ^ 8'hE2)}} & mem_out_E2) |
        ({8{~|(addr ^ 8'hE3)}} & mem_out_E3) |
        ({8{~|(addr ^ 8'hE4)}} & mem_out_E4) |
        ({8{~|(addr ^ 8'hE5)}} & mem_out_E5) |
        ({8{~|(addr ^ 8'hE6)}} & mem_out_E6) |
        ({8{~|(addr ^ 8'hE7)}} & mem_out_E7) |
        ({8{~|(addr ^ 8'hE8)}} & mem_out_E8) |
        ({8{~|(addr ^ 8'hE9)}} & mem_out_E9) |
        ({8{~|(addr ^ 8'hEA)}} & mem_out_EA) |
        ({8{~|(addr ^ 8'hEB)}} & mem_out_EB) |
        ({8{~|(addr ^ 8'hEC)}} & mem_out_EC) |
        ({8{~|(addr ^ 8'hED)}} & mem_out_ED) |
        ({8{~|(addr ^ 8'hEE)}} & mem_out_EE) |
        ({8{~|(addr ^ 8'hEF)}} & mem_out_EF) |
        ({8{~|(addr ^ 8'hF0)}} & mem_out_F0) |
        ({8{~|(addr ^ 8'hF1)}} & mem_out_F1) |
        ({8{~|(addr ^ 8'hF2)}} & mem_out_F2) |
        ({8{~|(addr ^ 8'hF3)}} & mem_out_F3) |
        ({8{~|(addr ^ 8'hF4)}} & mem_out_F4) |
        ({8{~|(addr ^ 8'hF5)}} & mem_out_F5) |
        ({8{~|(addr ^ 8'hF6)}} & mem_out_F6) |
        ({8{~|(addr ^ 8'hF7)}} & mem_out_F7) |
        ({8{~|(addr ^ 8'hF8)}} & mem_out_F8) |
        ({8{~|(addr ^ 8'hF9)}} & mem_out_F9) |
        ({8{~|(addr ^ 8'hFA)}} & mem_out_FA) |
        ({8{~|(addr ^ 8'hFB)}} & mem_out_FB) |
        ({8{~|(addr ^ 8'hFC)}} & mem_out_FC) |
        ({8{~|(addr ^ 8'hFD)}} & mem_out_FD) |
        ({8{~|(addr ^ 8'hFE)}} & mem_out_FE) |
        ({8{~|(addr ^ 8'hFF)}} & mem_out_FF);

endmodule
