// ============================================================================
// WARNING: THIS FILE WAS AUTO-GENERATED BY RUST ROM_BUILDER!
// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN DURING SYNTHESIS.
// ============================================================================
`timescale 1ns / 1ps

module instruction_memory (
    input  wire [15:0] read_addr,
    output reg  [15:0] instruction_out
);

    // Combinational MUX Logic (Synthesizes directly to ROM gates)
    always @(*) begin
        case (read_addr)
            16'h0000: instruction_out = 16'h81FF;
            16'h0001: instruction_out = 16'h820F;
            16'h0002: instruction_out = 16'h5312;
            16'h0003: instruction_out = 16'h6411;
            16'h0004: instruction_out = 16'h7520;
            16'h0005: instruction_out = 16'h1000;

            // Default safety ground to prevent floating wires (Latch Inference)
            default: instruction_out = 16'h0000;
        endcase
    end
endmodule
