use std::fs::File;
use std::io::Write;

fn main() -> std::io::Result<()> {
    // Output file path
    let mut f = File::create("../../src/data_memory.v")?;

    writeln!(f, "`timescale 1ns / 1ps")?;
    writeln!(f, "// ============================================================================")?;
    writeln!(f, "// WARNING: THIS FILE WAS AUTO-GENERATED BY RUST RAM_BUILDER!")?;
    writeln!(f, "// DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.")?;
    writeln!(f, "// ============================================================================")?;
    writeln!(f, "\nmodule data_memory (")?;
    writeln!(f, "    input wire clk,")?;
    writeln!(f, "    input wire rst,")?;
    writeln!(f, "    input wire we,              // Global Write Enable")?;
    writeln!(f, "    input wire [7:0] addr,")?;
    writeln!(f, "    input wire [7:0] data_in,")?;
    writeln!(f, "    output wire [7:0] data_out")?;
    writeln!(f, ");\n")?;

    writeln!(f, "    // --- Internal Wires ---")?;
    for i in 0..256 {
        writeln!(f, "    wire [7:0] mem_out_{:02X};", i)?;
        writeln!(f, "    wire we_{:02X};", i)?;
    }

    writeln!(f, "\n    // --- Write Address Decoder (8-to-256 DEMUX) ---")?;
    for i in 0..256 {
        writeln!(f, "    assign we_{:02X} = we & ~|(addr ^ 8'h{:02X});", i, i)?;
    }

    writeln!(f, "\n    // --- Physical Register Cells (256 Bytes / 2048 D-Flip-Flops) ---")?;
    for i in 0..256 {
        writeln!(f, "    cpu_register #(.WIDTH(8)) cell_{:02X} (", i)?;
        writeln!(f, "        .clk(clk), .rst(rst), .we(we_{:02X}), .data_in(data_in), .data_out(mem_out_{:02X})", i, i)?;
        writeln!(f, "    );")?;
    }

    writeln!(f, "\n    // --- Read Multiplexer (256-to-1 MUX) ---")?;
    writeln!(f, "    assign data_out =")?;
    for i in 0..256 {
        let or_char = if i == 255 { ";" } else { " |" };
        writeln!(f, "        ({{8{{~|(addr ^ 8'h{:02X})}}}} & mem_out_{:02X}){}", i, i, or_char)?;
    }

    writeln!(f, "\nendmodule")?;
    
    println!("Success! Pure gate-level data_memory.v (256 Bytes) has been generated.");
    Ok(())
}